/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* Define the flexspi macro. Note that it can't be modified here */
#define IOMUXC_GPIO_AD_B1_00_FLEXSPI_A_DATA03 0x401F80FCU, 0x1U, 0x401F8374U, 0x1U, 0x401F8270U
#define IOMUXC_GPIO_AD_B1_01_FLEXSPI_A_SCLK 0x401F8100U, 0x1U, 0x401F8378U, 0x1U, 0x401F8274U
#define IOMUXC_GPIO_AD_B1_02_FLEXSPI_A_DATA00 0x401F8104U, 0x1U, 0x401F8368U, 0x1U, 0x401F8278U
#define IOMUXC_GPIO_AD_B1_03_FLEXSPI_A_DATA02 0x401F8108U, 0x1U, 0x401F8370U, 0x1U, 0x401F827CU
#define IOMUXC_GPIO_AD_B1_04_FLEXSPI_A_DATA01 0x401F810CU, 0x1U, 0x401F836CU, 0x1U, 0x401F8280U
#define IOMUXC_GPIO_AD_B1_05_FLEXSPI_A_SS0_B 0x401F8110U, 0x1U, 0, 0, 0x401F8284U

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);

/* GPIO_AD_B0_14 (number 94), ENET_TXD0/U11[24]/J17[14] */
#define BOARD_INITPWM_ENET_TXD0_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_TXD0_SIGNAL                                         A   /*!< PWM2 signal: A */
#define BOARD_INITPWM_ENET_TXD0_CHANNEL                                       0U   /*!< PWM2 A channel: 0 */

/* GPIO_AD_B0_15 (number 93), ENET_TXD1/U11[25]/J19[4] */
#define BOARD_INITPWM_ENET_TXD1_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_TXD1_SIGNAL                                         B   /*!< PWM2 signal: B */
#define BOARD_INITPWM_ENET_TXD1_CHANNEL                                       0U   /*!< PWM2 B channel: 0 */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[8] */
#define BOARD_INITPWM_ENET_RXER_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_RXER_SIGNAL                                         A   /*!< PWM2 signal: A */
#define BOARD_INITPWM_ENET_RXER_CHANNEL                                       1U   /*!< PWM2 A channel: 1 */

/* GPIO_AD_B0_13 (number 95), ENET_TXEN/U11[23]/J19[10] */
#define BOARD_INITPWM_ENET_TXEN_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_TXEN_SIGNAL                                         B   /*!< PWM2 signal: B */
#define BOARD_INITPWM_ENET_TXEN_CHANNEL                                       1U   /*!< PWM2 B channel: 1 */

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[12] */
#define BOARD_INITPWM_ENET_RXD0_PERIPHERAL                                  PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_RXD0_SIGNAL                                         A   /*!< PWM2 signal: A */
#define BOARD_INITPWM_ENET_RXD0_CHANNEL                                       2U   /*!< PWM2 A channel: 2 */

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[6] */
#define BOARD_INITPWM_ENET_CRS_DV_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWM_ENET_CRS_DV_SIGNAL                                       B   /*!< PWM2 signal: B */
#define BOARD_INITPWM_ENET_CRS_DV_CHANNEL                                     2U   /*!< PWM2 B channel: 2 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM(void);

/* GPIO_AD_B1_10 (number 80), USB_OTG1_PWR/J18[2] */
#define DOARD_INITADC_CUR_A_PERIPHERAL                                      ADC1   /*!< Device name: ADC1 */
#define DOARD_INITADC_CUR_A_SIGNAL                                            IN   /*!< ADC1 signal: IN */
#define DOARD_INITADC_CUR_A_CHANNEL                                          10U   /*!< ADC1 IN channel: 10 */

/* GPIO_AD_B1_11 (number 79), USB_OTG1_ID/J18[4] */
#define DOARD_INITADC_CUR_B_PERIPHERAL                                      ADC1   /*!< Device name: ADC1 */
#define DOARD_INITADC_CUR_B_SIGNAL                                            IN   /*!< ADC1 signal: IN */
#define DOARD_INITADC_CUR_B_CHANNEL                                          11U   /*!< ADC1 IN channel: 11 */

/* GPIO_AD_B1_13 (number 76), CAN_STBY/J18[8] */
#define DOARD_INITADC_CUR_C_PERIPHERAL                                      ADC1   /*!< Device name: ADC1 */
#define DOARD_INITADC_CUR_C_SIGNAL                                            IN   /*!< ADC1 signal: IN */
#define DOARD_INITADC_CUR_C_CHANNEL                                          13U   /*!< ADC1 IN channel: 13 */

/* GPIO_AD_B1_12 (number 78), USB_OTG1_OC/J18[6] */
#define DOARD_INITADC_VOLT_DCB_PERIPHERAL                                   ADC1   /*!< Device name: ADC1 */
#define DOARD_INITADC_VOLT_DCB_SIGNAL                                         IN   /*!< ADC1 signal: IN */
#define DOARD_INITADC_VOLT_DCB_CHANNEL                                       12U   /*!< ADC1 IN channel: 12 */

/* GPIO_EMC_26 (number 130), SEMC_A11/U14[35]/BT_CFG[8] */
#define DOARD_INITADC_SEMC_A11_PERIPHERAL                                   PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A11_SIGNAL                                          A   /*!< PWM1 signal: A */
#define DOARD_INITADC_SEMC_A11_CHANNEL                                        0U   /*!< PWM1 A channel: 0 */

/* GPIO_EMC_24 (number 132), SEMC_A8/U14[33]/BT_CFG[6] */
#define DOARD_INITADC_SEMC_A8_PERIPHERAL                                    PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A8_SIGNAL                                           A   /*!< PWM1 signal: A */
#define DOARD_INITADC_SEMC_A8_CHANNEL                                         1U   /*!< PWM1 A channel: 1 */

/* GPIO_EMC_22 (number 136), SEMC_A6/U14[31]/BT_CFG[4] */
#define DOARD_INITADC_SEMC_A6_PERIPHERAL                                    PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A6_SIGNAL                                           A   /*!< PWM1 signal: A */
#define DOARD_INITADC_SEMC_A6_CHANNEL                                         2U   /*!< PWM1 A channel: 2 */

/* GPIO_EMC_27 (number 129), SEMC_A12/U14[36]/BT_CFG[9] */
#define DOARD_INITADC_SEMC_A12_PERIPHERAL                                   PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A12_SIGNAL                                          B   /*!< PWM1 signal: B */
#define DOARD_INITADC_SEMC_A12_CHANNEL                                        0U   /*!< PWM1 B channel: 0 */

/* GPIO_EMC_25 (number 131), SEMC_A9/U14[34]/BT_CFG[7] */
#define DOARD_INITADC_SEMC_A9_PERIPHERAL                                    PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A9_SIGNAL                                           B   /*!< PWM1 signal: B */
#define DOARD_INITADC_SEMC_A9_CHANNEL                                         1U   /*!< PWM1 B channel: 1 */

/* GPIO_EMC_23 (number 133), SEMC_A7/U14[32]/BT_CFG[5] */
#define DOARD_INITADC_SEMC_A7_PERIPHERAL                                    PWM1   /*!< Device name: PWM1 */
#define DOARD_INITADC_SEMC_A7_SIGNAL                                           B   /*!< PWM1 signal: B */
#define DOARD_INITADC_SEMC_A7_CHANNEL                                         2U   /*!< PWM1 B channel: 2 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void DOARD_InitADC(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENC(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCMP(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
