/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* Define the flexspi macro. Note that it can't be modified here */
#define IOMUXC_GPIO_AD_B1_00_FLEXSPI_A_DATA03 0x401F80FCU, 0x1U, 0x401F8374U, 0x1U, 0x401F8270U
#define IOMUXC_GPIO_AD_B1_01_FLEXSPI_A_SCLK 0x401F8100U, 0x1U, 0x401F8378U, 0x1U, 0x401F8274U
#define IOMUXC_GPIO_AD_B1_02_FLEXSPI_A_DATA00 0x401F8104U, 0x1U, 0x401F8368U, 0x1U, 0x401F8278U
#define IOMUXC_GPIO_AD_B1_03_FLEXSPI_A_DATA02 0x401F8108U, 0x1U, 0x401F8370U, 0x1U, 0x401F827CU
#define IOMUXC_GPIO_AD_B1_04_FLEXSPI_A_DATA01 0x401F810CU, 0x1U, 0x401F836CU, 0x1U, 0x401F8280U
#define IOMUXC_GPIO_AD_B1_05_FLEXSPI_A_SS0_B 0x401F8110U, 0x1U, 0, 0, 0x401F8284U

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), CURR1_DCB */
#define BOARD_INITADCPINS_CURR1_DCB_PERIPHERAL                              ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR1_DCB_SIGNAL                                    IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR1_DCB_CHANNEL                                   1U   /*!< ADC1 IN channel: 1 */
#define BOARD_INITADCPINS_CURR1_DCB_PIN_NAME                       GPIO_AD_B0_12   /*!< Pin name */
#define BOARD_INITADCPINS_CURR1_DCB_LABEL                            "CURR1_DCB"   /*!< Label */
#define BOARD_INITADCPINS_CURR1_DCB_NAME                             "CURR1_DCB"   /*!< Identifier name */

/* GPIO_AD_B0_13 (coord L14), VOLT1_DCB */
#define BOARD_INITADCPINS_VOLT1_DCB_PERIPHERAL                              ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_VOLT1_DCB_SIGNAL                                    IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_VOLT1_DCB_CHANNEL                                   2U   /*!< ADC1 IN channel: 2 */
#define BOARD_INITADCPINS_VOLT1_DCB_PIN_NAME                       GPIO_AD_B0_13   /*!< Pin name */
#define BOARD_INITADCPINS_VOLT1_DCB_LABEL                            "VOLT1_DCB"   /*!< Label */
#define BOARD_INITADCPINS_VOLT1_DCB_NAME                             "VOLT1_DCB"   /*!< Identifier name */

/* GPIO_AD_B0_14 (coord H14), CURR2_DCB */
#define BOARD_INITADCPINS_CURR2_DCB_PERIPHERAL                              ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR2_DCB_SIGNAL                                    IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR2_DCB_CHANNEL                                   3U   /*!< ADC1 IN channel: 3 */
#define BOARD_INITADCPINS_CURR2_DCB_PIN_NAME                       GPIO_AD_B0_14   /*!< Pin name */
#define BOARD_INITADCPINS_CURR2_DCB_LABEL                            "CURR2_DCB"   /*!< Label */
#define BOARD_INITADCPINS_CURR2_DCB_NAME                             "CURR2_DCB"   /*!< Identifier name */

/* GPIO_AD_B0_15 (coord L10), VOLT2_DCB */
#define BOARD_INITADCPINS_VOLT2_DCB_PERIPHERAL                              ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_VOLT2_DCB_SIGNAL                                    IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_VOLT2_DCB_CHANNEL                                   4U   /*!< ADC1 IN channel: 4 */
#define BOARD_INITADCPINS_VOLT2_DCB_PIN_NAME                       GPIO_AD_B0_15   /*!< Pin name */
#define BOARD_INITADCPINS_VOLT2_DCB_LABEL                            "VOLT2_DCB"   /*!< Label */
#define BOARD_INITADCPINS_VOLT2_DCB_NAME                             "VOLT2_DCB"   /*!< Identifier name */

/* GPIO_AD_B1_00 (coord J11), CURR1_A */
#define BOARD_INITADCPINS_CURR1_A_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR1_A_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR1_A_CHANNEL                                     5U   /*!< ADC1 IN channel: 5 */
#define BOARD_INITADCPINS_CURR1_A_PIN_NAME                         GPIO_AD_B1_00   /*!< Pin name */
#define BOARD_INITADCPINS_CURR1_A_LABEL                                "CURR1_A"   /*!< Label */
#define BOARD_INITADCPINS_CURR1_A_NAME                                 "CURR1_A"   /*!< Identifier name */

/* GPIO_AD_B1_01 (coord K11), CURR1_B */
#define BOARD_INITADCPINS_CURR1_B_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR1_B_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR1_B_CHANNEL                                     6U   /*!< ADC1 IN channel: 6 */
#define BOARD_INITADCPINS_CURR1_B_PIN_NAME                         GPIO_AD_B1_01   /*!< Pin name */
#define BOARD_INITADCPINS_CURR1_B_LABEL                                "CURR1_B"   /*!< Label */
#define BOARD_INITADCPINS_CURR1_B_NAME                                 "CURR1_B"   /*!< Identifier name */

/* GPIO_AD_B1_02 (coord L11), CURR1_C */
#define BOARD_INITADCPINS_CURR1_C_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR1_C_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR1_C_CHANNEL                                     7U   /*!< ADC1 IN channel: 7 */
#define BOARD_INITADCPINS_CURR1_C_PIN_NAME                         GPIO_AD_B1_02   /*!< Pin name */
#define BOARD_INITADCPINS_CURR1_C_LABEL                                "CURR1_C"   /*!< Label */
#define BOARD_INITADCPINS_CURR1_C_NAME                                 "CURR1_C"   /*!< Identifier name */

/* GPIO_AD_B1_03 (coord M12), CURR2_A */
#define BOARD_INITADCPINS_CURR2_A_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR2_A_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR2_A_CHANNEL                                     8U   /*!< ADC1 IN channel: 8 */
#define BOARD_INITADCPINS_CURR2_A_PIN_NAME                         GPIO_AD_B1_03   /*!< Pin name */
#define BOARD_INITADCPINS_CURR2_A_LABEL                                "CURR2_A"   /*!< Label */
#define BOARD_INITADCPINS_CURR2_A_NAME                                 "CURR2_A"   /*!< Identifier name */

/* GPIO_AD_B1_04 (coord L12), CURR2_B */
#define BOARD_INITADCPINS_CURR2_B_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR2_B_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR2_B_CHANNEL                                     9U   /*!< ADC1 IN channel: 9 */
#define BOARD_INITADCPINS_CURR2_B_PIN_NAME                         GPIO_AD_B1_04   /*!< Pin name */
#define BOARD_INITADCPINS_CURR2_B_LABEL                                "CURR2_B"   /*!< Label */
#define BOARD_INITADCPINS_CURR2_B_NAME                                 "CURR2_B"   /*!< Identifier name */

/* GPIO_AD_B1_05 (coord K12), CURR2_C */
#define BOARD_INITADCPINS_CURR2_C_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITADCPINS_CURR2_C_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITADCPINS_CURR2_C_CHANNEL                                    10U   /*!< ADC1 IN channel: 10 */
#define BOARD_INITADCPINS_CURR2_C_PIN_NAME                         GPIO_AD_B1_05   /*!< Pin name */
#define BOARD_INITADCPINS_CURR2_C_LABEL                                "CURR2_C"   /*!< Label */
#define BOARD_INITADCPINS_CURR2_C_NAME                                 "CURR2_C"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitAdcPins(void);

/* GPIO_EMC_23 (coord G2), PWM1_AT */
#define BOARD_INITPWMPINS_PWM1_AT_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_AT_SIGNAL                                       A   /*!< PWM1 signal: A */
#define BOARD_INITPWMPINS_PWM1_AT_CHANNEL                                     0U   /*!< PWM1 A channel: 0 */
#define BOARD_INITPWMPINS_PWM1_AT_PIN_NAME                           GPIO_EMC_26   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_AT_LABEL                                "PWM1_AT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_AT_NAME                                 "PWM1_AT"   /*!< Identifier name */

/* GPIO_EMC_24 (coord D3), PWM1_AB */
#define BOARD_INITPWMPINS_PWM1_AB_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_AB_SIGNAL                                       B   /*!< PWM1 signal: B */
#define BOARD_INITPWMPINS_PWM1_AB_CHANNEL                                     0U   /*!< PWM1 B channel: 0 */
#define BOARD_INITPWMPINS_PWM1_AB_PIN_NAME                           GPIO_EMC_27   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_AB_LABEL                                "PWM1_AB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_AB_NAME                                 "PWM1_AB"   /*!< Identifier name */

/* GPIO_EMC_25 (coord D2), PWM1_BT */
#define BOARD_INITPWMPINS_PWM1_BT_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_BT_SIGNAL                                       A   /*!< PWM1 signal: A */
#define BOARD_INITPWMPINS_PWM1_BT_CHANNEL                                     1U   /*!< PWM1 A channel: 1 */
#define BOARD_INITPWMPINS_PWM1_BT_PIN_NAME                           GPIO_EMC_24   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_BT_LABEL                                "PWM1_BT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_BT_NAME                                 "PWM1_BT"   /*!< Identifier name */

/* GPIO_EMC_26 (coord B3), PWM1_BB */
#define BOARD_INITPWMPINS_PWM1_BB_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_BB_SIGNAL                                       B   /*!< PWM1 signal: B */
#define BOARD_INITPWMPINS_PWM1_BB_CHANNEL                                     1U   /*!< PWM1 B channel: 1 */
#define BOARD_INITPWMPINS_PWM1_BB_PIN_NAME                           GPIO_EMC_25   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_BB_LABEL                                "PWM1_BB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_BB_NAME                                 "PWM1_BB"   /*!< Identifier name */

/* GPIO_EMC_27 (coord A2), PWM1_CT */
#define BOARD_INITPWMPINS_PWM1_CT_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_CT_SIGNAL                                       A   /*!< PWM1 signal: A */
#define BOARD_INITPWMPINS_PWM1_CT_CHANNEL                                     2U   /*!< PWM1 A channel: 2 */
#define BOARD_INITPWMPINS_PWM1_CT_PIN_NAME                           GPIO_EMC_22   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_CT_LABEL                                "PWM1_CT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_CT_NAME                                 "PWM1_CT"   /*!< Identifier name */

/* GPIO_EMC_28 (coord D1), PWM1_CB */
#define BOARD_INITPWMPINS_PWM1_CB_PERIPHERAL                                PWM1   /*!< Device name: PWM1 */
#define BOARD_INITPWMPINS_PWM1_CB_SIGNAL                                       B   /*!< PWM1 signal: B */
#define BOARD_INITPWMPINS_PWM1_CB_CHANNEL                                     2U   /*!< PWM1 B channel: 2 */
#define BOARD_INITPWMPINS_PWM1_CB_PIN_NAME                           GPIO_EMC_23   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM1_CB_LABEL                                "PWM1_CB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM1_CB_NAME                                 "PWM1_CB"   /*!< Identifier name */

/* GPIO_AD_B0_14, PWM2_AT */
#define BOARD_INITPWMPINS_PWM2_AT_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_AT_SIGNAL                                       A   /*!< PWM2 signal: A */
#define BOARD_INITPWMPINS_PWM2_AT_CHANNEL                                     0U   /*!< PWM2 A channel: 0 */
#define BOARD_INITPWMPINS_PWM2_AT_PIN_NAME                         GPIO_AD_B0_14   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_AT_LABEL                                "PWM2_AT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_AT_NAME                                 "PWM2_AT"   /*!< Identifier name */

/* GPIO_AD_B0_15, PWM2_AB */
#define BOARD_INITPWMPINS_PWM2_AB_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_AB_SIGNAL                                       B   /*!< PWM2 signal: B */
#define BOARD_INITPWMPINS_PWM2_AB_CHANNEL                                     0U   /*!< PWM2 B channel: 0 */
#define BOARD_INITPWMPINS_PWM2_AB_PIN_NAME                         GPIO_AD_B0_15   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_AB_LABEL                                "PWM2_AB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_AB_NAME                                 "PWM2_AB"   /*!< Identifier name */

/* GPIO_AD_B0_12, PWM2_BT */
#define BOARD_INITPWMPINS_PWM2_BT_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_BT_SIGNAL                                       A   /*!< PWM2 signal: A */
#define BOARD_INITPWMPINS_PWM2_BT_CHANNEL                                     1U   /*!< PWM2 A channel: 1 */
#define BOARD_INITPWMPINS_PWM2_BT_PIN_NAME                         GPIO_AD_B0_12   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_BT_LABEL                                "PWM2_BT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_BT_NAME                                 "PWM2_BT"   /*!< Identifier name */

/* GPIO_AD_B0_13, PWM2_BB */
#define BOARD_INITPWMPINS_PWM2_BB_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_BB_SIGNAL                                       B   /*!< PWM2 signal: B */
#define BOARD_INITPWMPINS_PWM2_BB_CHANNEL                                     1U   /*!< PWM2 B channel: 1 */
#define BOARD_INITPWMPINS_PWM2_BB_PIN_NAME                         GPIO_AD_B0_13   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_BB_LABEL                                "PWM2_BB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_BB_NAME                                 "PWM2_BB"   /*!< Identifier name */

/* GPIO_AD_B0_10, PWM2_CT */
#define BOARD_INITPWMPINS_PWM2_CT_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_CT_SIGNAL                                       A   /*!< PWM2 signal: A */
#define BOARD_INITPWMPINS_PWM2_CT_CHANNEL                                     3U   /*!< PWM2 A channel: 3 */
#define BOARD_INITPWMPINS_PWM2_CT_PIN_NAME                         GPIO_AD_B0_10   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_CT_LABEL                                "PWM2_CT"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_CT_NAME                                 "PWM2_CT"   /*!< Identifier name */

/* GPIO_AD_B0_11, PWM2_CB */
#define BOARD_INITPWMPINS_PWM2_CB_PERIPHERAL                                PWM2   /*!< Device name: PWM2 */
#define BOARD_INITPWMPINS_PWM2_CB_SIGNAL                                       B   /*!< PWM2 signal: B */
#define BOARD_INITPWMPINS_PWM2_CB_CHANNEL                                     3U   /*!< PWM2 B channel: 3 */
#define BOARD_INITPWMPINS_PWM2_CB_PIN_NAME                         GPIO_AD_B0_11   /*!< Pin name */
#define BOARD_INITPWMPINS_PWM2_CB_LABEL                                "PWM2_CB"   /*!< Label */
#define BOARD_INITPWMPINS_PWM2_CB_NAME                                 "PWM2_CB"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPwmPins(void);

/* GPIO_EMC_35 (coord E5), ENC1_A */
#define BOARD_INITENCPINS_ENC1_A_PERIPHERAL                                 ENC1   /*!< Device name: ENC1 */
#define BOARD_INITENCPINS_ENC1_A_SIGNAL                                    PHASE   /*!< ENC1 signal: PHASE */
#define BOARD_INITENCPINS_ENC1_A_CHANNEL                                       A   /*!< ENC1 PHASE channel: A */
#define BOARD_INITENCPINS_ENC1_A_PIN_NAME                            GPIO_EMC_35   /*!< Pin name */
#define BOARD_INITENCPINS_ENC1_A_LABEL                                  "ENC1_A"   /*!< Label */
#define BOARD_INITENCPINS_ENC1_A_NAME                                   "ENC1_A"   /*!< Identifier name */

/* GPIO_EMC_36 (coord C3), ENC1_B */
#define BOARD_INITENCPINS_ENC1_B_PERIPHERAL                                 ENC1   /*!< Device name: ENC1 */
#define BOARD_INITENCPINS_ENC1_B_SIGNAL                                    PHASE   /*!< ENC1 signal: PHASE */
#define BOARD_INITENCPINS_ENC1_B_CHANNEL                                       B   /*!< ENC1 PHASE channel: B */
#define BOARD_INITENCPINS_ENC1_B_PIN_NAME                            GPIO_EMC_36   /*!< Pin name */
#define BOARD_INITENCPINS_ENC1_B_LABEL                                  "ENC1_B"   /*!< Label */
#define BOARD_INITENCPINS_ENC1_B_NAME                                   "ENC1_B"   /*!< Identifier name */

/* GPIO_EMC_37 (coord E4), ENC1_I */
#define BOARD_INITENCPINS_ENC1_I_PERIPHERAL                                 ENC1   /*!< Device name: ENC1 */
#define BOARD_INITENCPINS_ENC1_I_SIGNAL                                    INDEX   /*!< ENC1 signal: INDEX */
#define BOARD_INITENCPINS_ENC1_I_PIN_NAME                            GPIO_EMC_37   /*!< Pin name */
#define BOARD_INITENCPINS_ENC1_I_LABEL                                  "ENC1_I"   /*!< Label */
#define BOARD_INITENCPINS_ENC1_I_NAME                                   "ENC1_I"   /*!< Identifier name */

/* GPIO_EMC_13 (coord A6), ENC2_A */
#define BOARD_INITENCPINS_ENC2_A_PERIPHERAL                                 ENC2   /*!< Device name: ENC2 */
#define BOARD_INITENCPINS_ENC2_A_SIGNAL                                    PHASE   /*!< ENC2 signal: PHASE */
#define BOARD_INITENCPINS_ENC2_A_CHANNEL                                       A   /*!< ENC2 PHASE channel: A */
#define BOARD_INITENCPINS_ENC2_A_PIN_NAME                            GPIO_EMC_13   /*!< Pin name */
#define BOARD_INITENCPINS_ENC2_A_LABEL                                  "ENC2_A"   /*!< Label */
#define BOARD_INITENCPINS_ENC2_A_NAME                                   "ENC2_A"   /*!< Identifier name */

/* GPIO_EMC_14 (coord B6), ENC2_B */
#define BOARD_INITENCPINS_ENC2_B_PERIPHERAL                                 ENC2   /*!< Device name: ENC2 */
#define BOARD_INITENCPINS_ENC2_B_SIGNAL                                    PHASE   /*!< ENC2 signal: PHASE */
#define BOARD_INITENCPINS_ENC2_B_CHANNEL                                       B   /*!< ENC2 PHASE channel: B */
#define BOARD_INITENCPINS_ENC2_B_PIN_NAME                            GPIO_EMC_14   /*!< Pin name */
#define BOARD_INITENCPINS_ENC2_B_LABEL                                  "ENC2_B"   /*!< Label */
#define BOARD_INITENCPINS_ENC2_B_NAME                                   "ENC2_B"   /*!< Identifier name */

/* GPIO_B0_15 (coord E11), ENC2_I */
#define BOARD_INITENCPINS_ENC2_I_PERIPHERAL                                 ENC2   /*!< Device name: ENC2 */
#define BOARD_INITENCPINS_ENC2_I_SIGNAL                                    INDEX   /*!< ENC2 signal: INDEX */
#define BOARD_INITENCPINS_ENC2_I_PIN_NAME                             GPIO_B0_15   /*!< Pin name */
#define BOARD_INITENCPINS_ENC2_I_LABEL                                  "ENC2_I"   /*!< Label */
#define BOARD_INITENCPINS_ENC2_I_NAME                                   "ENC2_I"   /*!< Identifier name */

/* GPIO_EMC_15 (coord B1), ENC3_A */
#define BOARD_INITENCPINS_ENC3_A_PERIPHERAL                                 ENC3   /*!< Device name: ENC3 */
#define BOARD_INITENCPINS_ENC3_A_SIGNAL                                    PHASE   /*!< ENC3 signal: PHASE */
#define BOARD_INITENCPINS_ENC3_A_CHANNEL                                       A   /*!< ENC3 PHASE channel: A */
#define BOARD_INITENCPINS_ENC3_A_PIN_NAME                            GPIO_EMC_15   /*!< Pin name */
#define BOARD_INITENCPINS_ENC3_A_LABEL                                  "ENC3_A"   /*!< Label */
#define BOARD_INITENCPINS_ENC3_A_NAME                                   "ENC3_A"   /*!< Identifier name */

/* GPIO_EMC_16 (coord A5), ENC3_B */
#define BOARD_INITENCPINS_ENC3_B_PERIPHERAL                                 ENC3   /*!< Device name: ENC3 */
#define BOARD_INITENCPINS_ENC3_B_SIGNAL                                    PHASE   /*!< ENC3 signal: PHASE */
#define BOARD_INITENCPINS_ENC3_B_CHANNEL                                       B   /*!< ENC3 PHASE channel: B */
#define BOARD_INITENCPINS_ENC3_B_PIN_NAME                            GPIO_EMC_16   /*!< Pin name */
#define BOARD_INITENCPINS_ENC3_B_LABEL                                  "ENC3_B"   /*!< Label */
#define BOARD_INITENCPINS_ENC3_B_NAME                                   "ENC3_B"   /*!< Identifier name */

/* GPIO_B1_00 (coord A11), ENC3_I */
#define BOARD_INITENCPINS_ENC3_I_PERIPHERAL                                 ENC3   /*!< Device name: ENC3 */
#define BOARD_INITENCPINS_ENC3_I_SIGNAL                                    INDEX   /*!< ENC3 signal: INDEX */
#define BOARD_INITENCPINS_ENC3_I_PIN_NAME                             GPIO_B1_00   /*!< Pin name */
#define BOARD_INITENCPINS_ENC3_I_LABEL                                  "ENC3_I"   /*!< Label */
#define BOARD_INITENCPINS_ENC3_I_NAME                                   "ENC3_I"   /*!< Identifier name */

/* GPIO_B1_01 (coord B11), ENC4_A */
#define BOARD_INITENCPINS_ENC4_A_PERIPHERAL                                 ENC4   /*!< Device name: ENC4 */
#define BOARD_INITENCPINS_ENC4_A_SIGNAL                                    PHASE   /*!< ENC4 signal: PHASE */
#define BOARD_INITENCPINS_ENC4_A_CHANNEL                                       A   /*!< ENC4 PHASE channel: A */
#define BOARD_INITENCPINS_ENC4_A_PIN_NAME                             GPIO_B1_01   /*!< Pin name */
#define BOARD_INITENCPINS_ENC4_A_LABEL                                  "ENC4_A"   /*!< Label */
#define BOARD_INITENCPINS_ENC4_A_NAME                                   "ENC4_A"   /*!< Identifier name */

/* GPIO_B1_02 (coord C11), ENC4_B */
#define BOARD_INITENCPINS_ENC4_B_PERIPHERAL                                 ENC4   /*!< Device name: ENC4 */
#define BOARD_INITENCPINS_ENC4_B_SIGNAL                                    PHASE   /*!< ENC4 signal: PHASE */
#define BOARD_INITENCPINS_ENC4_B_CHANNEL                                       B   /*!< ENC4 PHASE channel: B */
#define BOARD_INITENCPINS_ENC4_B_PIN_NAME                             GPIO_B1_02   /*!< Pin name */
#define BOARD_INITENCPINS_ENC4_B_LABEL                                  "ENC4_B"   /*!< Label */
#define BOARD_INITENCPINS_ENC4_B_NAME                                   "ENC4_B"   /*!< Identifier name */

/* GPIO_B1_03 (coord D11), ENC4_I */
#define BOARD_INITENCPINS_ENC4_I_PERIPHERAL                                 ENC4   /*!< Device name: ENC4 */
#define BOARD_INITENCPINS_ENC4_I_SIGNAL                                    INDEX   /*!< ENC4 signal: INDEX */
#define BOARD_INITENCPINS_ENC4_I_PIN_NAME                             GPIO_B1_03   /*!< Pin name */
#define BOARD_INITENCPINS_ENC4_I_LABEL                                  "ENC4_I"   /*!< Label */
#define BOARD_INITENCPINS_ENC4_I_NAME                                   "ENC4_I"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEncPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLcdPins(void);

/* GPIO_EMC_17 (coord A4), FLEXCAN1_TX */
#define BOARD_INITCANPINS_FLEXCAN1_TX_PERIPHERAL                            CAN1   /*!< Device name: CAN1 */
#define BOARD_INITCANPINS_FLEXCAN1_TX_SIGNAL                                  TX   /*!< CAN1 signal: TX */
#define BOARD_INITCANPINS_FLEXCAN1_TX_PIN_NAME                       GPIO_EMC_17   /*!< Pin name */
#define BOARD_INITCANPINS_FLEXCAN1_TX_LABEL                        "FLEXCAN1_TX"   /*!< Label */
#define BOARD_INITCANPINS_FLEXCAN1_TX_NAME                         "FLEXCAN1_TX"   /*!< Identifier name */

/* GPIO_EMC_18 (coord B2), FLEXCAN1_RX */
#define BOARD_INITCANPINS_FLEXCAN1_RX_PERIPHERAL                            CAN1   /*!< Device name: CAN1 */
#define BOARD_INITCANPINS_FLEXCAN1_RX_SIGNAL                                  RX   /*!< CAN1 signal: RX */
#define BOARD_INITCANPINS_FLEXCAN1_RX_PIN_NAME                       GPIO_EMC_18   /*!< Pin name */
#define BOARD_INITCANPINS_FLEXCAN1_RX_LABEL                        "FLEXCAN1_RX"   /*!< Label */
#define BOARD_INITCANPINS_FLEXCAN1_RX_NAME                         "FLEXCAN1_RX"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCanPins(void);

/* GPIO_B1_04 (coord E12), ENET_RX_DATA0 */
#define BOARD_INITENETPINS_ENET_RX_DATA0_PERIPHERAL                         ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_RX_DATA0_SIGNAL                     enet_rx_data   /*!< ENET signal: enet_rx_data */
#define BOARD_INITENETPINS_ENET_RX_DATA0_CHANNEL                              0U   /*!< ENET enet_rx_data channel: 0 */
#define BOARD_INITENETPINS_ENET_RX_DATA0_PIN_NAME                     GPIO_B1_04   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_RX_DATA0_LABEL                   "ENET_RX_DATA0"   /*!< Label */
#define BOARD_INITENETPINS_ENET_RX_DATA0_NAME                    "ENET_RX_DATA0"   /*!< Identifier name */

/* GPIO_B1_05 (coord D12), ENET_RX_DATA1 */
#define BOARD_INITENETPINS_ENET_RX_DATA1_PERIPHERAL                         ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_RX_DATA1_SIGNAL                     enet_rx_data   /*!< ENET signal: enet_rx_data */
#define BOARD_INITENETPINS_ENET_RX_DATA1_CHANNEL                              1U   /*!< ENET enet_rx_data channel: 1 */
#define BOARD_INITENETPINS_ENET_RX_DATA1_PIN_NAME                     GPIO_B1_05   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_RX_DATA1_LABEL                   "ENET_RX_DATA1"   /*!< Label */
#define BOARD_INITENETPINS_ENET_RX_DATA1_NAME                    "ENET_RX_DATA1"   /*!< Identifier name */

/* GPIO_B1_06 (coord C12), ENET_CRS_RV */
#define BOARD_INITENETPINS_ENET_CRS_RV_PERIPHERAL                           ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_CRS_RV_SIGNAL                         enet_rx_en   /*!< ENET signal: enet_rx_en */
#define BOARD_INITENETPINS_ENET_CRS_RV_PIN_NAME                       GPIO_B1_06   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_CRS_RV_LABEL                       "ENET_CRS_RV"   /*!< Label */
#define BOARD_INITENETPINS_ENET_CRS_RV_NAME                        "ENET_CRS_RV"   /*!< Identifier name */

/* GPIO_B1_07 (coord B12), ENET_TX_DATA0 */
#define BOARD_INITENETPINS_ENET_TX_DATA0_PERIPHERAL                         ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_TX_DATA0_SIGNAL                     enet_tx_data   /*!< ENET signal: enet_tx_data */
#define BOARD_INITENETPINS_ENET_TX_DATA0_CHANNEL                              0U   /*!< ENET enet_tx_data channel: 0 */
#define BOARD_INITENETPINS_ENET_TX_DATA0_PIN_NAME                     GPIO_B1_07   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_TX_DATA0_LABEL                   "ENET_TX_DATA0"   /*!< Label */
#define BOARD_INITENETPINS_ENET_TX_DATA0_NAME                    "ENET_TX_DATA0"   /*!< Identifier name */

/* GPIO_B1_08 (coord A12), ENET_TX_DATA1 */
#define BOARD_INITENETPINS_ENET_TX_DATA1_PERIPHERAL                         ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_TX_DATA1_SIGNAL                     enet_tx_data   /*!< ENET signal: enet_tx_data */
#define BOARD_INITENETPINS_ENET_TX_DATA1_CHANNEL                              1U   /*!< ENET enet_tx_data channel: 1 */
#define BOARD_INITENETPINS_ENET_TX_DATA1_PIN_NAME                     GPIO_B1_08   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_TX_DATA1_LABEL                   "ENET_TX_DATA1"   /*!< Label */
#define BOARD_INITENETPINS_ENET_TX_DATA1_NAME                    "ENET_TX_DATA1"   /*!< Identifier name */

/* GPIO_B1_09 (coord A13), ENET_TX_EN */
#define BOARD_INITENETPINS_ENET_TX_EN_PERIPHERAL                            ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_TX_EN_SIGNAL                          enet_tx_en   /*!< ENET signal: enet_tx_en */
#define BOARD_INITENETPINS_ENET_TX_EN_PIN_NAME                        GPIO_B1_09   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_TX_EN_LABEL                         "ENET_TX_EN"   /*!< Label */
#define BOARD_INITENETPINS_ENET_TX_EN_NAME                          "ENET_TX_EN"   /*!< Identifier name */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
#define BOARD_INITENETPINS_ENET_TX_CLK_PERIPHERAL                           ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_TX_CLK_SIGNAL                        enet_tx_clk   /*!< ENET signal: enet_tx_clk */
#define BOARD_INITENETPINS_ENET_TX_CLK_PIN_NAME                       GPIO_B1_10   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_TX_CLK_LABEL                       "ENET_TX_CLK"   /*!< Label */
#define BOARD_INITENETPINS_ENET_TX_CLK_NAME                        "ENET_TX_CLK"   /*!< Identifier name */

/* GPIO_B1_11 (coord C13), ENET_RX_ER */
#define BOARD_INITENETPINS_ENET_RX_ER_PERIPHERAL                            ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_RX_ER_SIGNAL                          enet_rx_er   /*!< ENET signal: enet_rx_er */
#define BOARD_INITENETPINS_ENET_RX_ER_PIN_NAME                        GPIO_B1_11   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_RX_ER_LABEL                         "ENET_RX_ER"   /*!< Label */
#define BOARD_INITENETPINS_ENET_RX_ER_NAME                          "ENET_RX_ER"   /*!< Identifier name */

/* GPIO_B1_14 (coord C14), ENET_MDC */
#define BOARD_INITENETPINS_ENET_MDC_PERIPHERAL                              ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_MDC_SIGNAL                              enet_mdc   /*!< ENET signal: enet_mdc */
#define BOARD_INITENETPINS_ENET_MDC_PIN_NAME                          GPIO_B1_14   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_MDC_LABEL                             "ENET_MDC"   /*!< Label */
#define BOARD_INITENETPINS_ENET_MDC_NAME                              "ENET_MDC"   /*!< Identifier name */

/* GPIO_B1_15 (coord B14), ENET_MDIO */
#define BOARD_INITENETPINS_ENET_MDIO_PERIPHERAL                             ENET   /*!< Device name: ENET */
#define BOARD_INITENETPINS_ENET_MDIO_SIGNAL                            enet_mdio   /*!< ENET signal: enet_mdio */
#define BOARD_INITENETPINS_ENET_MDIO_PIN_NAME                         GPIO_B1_15   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_MDIO_LABEL                           "ENET_MDIO"   /*!< Label */
#define BOARD_INITENETPINS_ENET_MDIO_NAME                            "ENET_MDIO"   /*!< Identifier name */

/* GPIO_AD_B0_09 (coord F14), ENET_RST */
#define BOARD_INITENETPINS_ENET_RST_GPIO                                   GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITENETPINS_ENET_RST_PORT                                   GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITENETPINS_ENET_RST_GPIO_PIN                                  9U   /*!< GPIO1 pin index: 9 */
#define BOARD_INITENETPINS_ENET_RST_PIN_NAME                       GPIO_AD_B0_09   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_RST_LABEL                             "ENET_RST"   /*!< Label */
#define BOARD_INITENETPINS_ENET_RST_NAME                              "ENET_RST"   /*!< Identifier name */
#define BOARD_INITENETPINS_ENET_RST_DIRECTION           kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_AD_B0_10 (coord G13), ENET_INT */
#define BOARD_INITENETPINS_ENET_INT_GPIO                                   GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITENETPINS_ENET_INT_PORT                                   GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITENETPINS_ENET_INT_GPIO_PIN                                 10U   /*!< GPIO1 pin index: 10 */
#define BOARD_INITENETPINS_ENET_INT_PIN_NAME                       GPIO_AD_B0_10   /*!< Pin name */
#define BOARD_INITENETPINS_ENET_INT_LABEL                             "ENET_INT"   /*!< Label */
#define BOARD_INITENETPINS_ENET_INT_NAME                              "ENET_INT"   /*!< Identifier name */
#define BOARD_INITENETPINS_ENET_INT_DIRECTION            kPIN_MUX_DirectionInput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEnetPins(void);

/* GPIO_SD_B1_00 (coord L5), FLEXSPI_B_DATA3 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA3_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA3_SIGNAL             FLEXSPI_B_DATA3   /*!< FLEXSPI signal: FLEXSPI_B_DATA3 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA3_PIN_NAME             GPIO_SD_B1_00   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA3_LABEL            "FLEXSPI_B_DATA3"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA3_NAME             "FLEXSPI_B_DATA3"   /*!< Identifier name */

/* GPIO_SD_B1_01 (coord M5), FLEXSPI_B_DATA2 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA2_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA2_SIGNAL             FLEXSPI_B_DATA2   /*!< FLEXSPI signal: FLEXSPI_B_DATA2 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA2_PIN_NAME             GPIO_SD_B1_01   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA2_LABEL            "FLEXSPI_B_DATA2"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA2_NAME             "FLEXSPI_B_DATA2"   /*!< Identifier name */

/* GPIO_SD_B1_02 (coord M3), FLEXSPI_B_DATA1 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA1_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA1_SIGNAL             FLEXSPI_B_DATA1   /*!< FLEXSPI signal: FLEXSPI_B_DATA1 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA1_PIN_NAME             GPIO_SD_B1_02   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA1_LABEL            "FLEXSPI_B_DATA1"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA1_NAME             "FLEXSPI_B_DATA1"   /*!< Identifier name */

/* GPIO_SD_B1_03 (coord M4), FLEXSPI_B_DATA0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA0_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA0_SIGNAL             FLEXSPI_B_DATA0   /*!< FLEXSPI signal: FLEXSPI_B_DATA0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA0_PIN_NAME             GPIO_SD_B1_03   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA0_LABEL            "FLEXSPI_B_DATA0"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_DATA0_NAME             "FLEXSPI_B_DATA0"   /*!< Identifier name */

/* GPIO_SD_B1_04 (coord P2), FLEXSPI_B_SCLK */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SCLK_PERIPHERAL                  FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SCLK_SIGNAL               FLEXSPI_B_SCLK   /*!< FLEXSPI signal: FLEXSPI_B_SCLK */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SCLK_PIN_NAME              GPIO_SD_B1_04   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SCLK_LABEL              "FLEXSPI_B_SCLK"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SCLK_NAME               "FLEXSPI_B_SCLK"   /*!< Identifier name */

/* GPIO_SD_B1_05 (coord N3), FLEXSPI_B_SS0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SS0_PERIPHERAL                   FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SS0_SIGNAL               FLEXSPI_B_SS0_B   /*!< FLEXSPI signal: FLEXSPI_B_SS0_B */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SS0_PIN_NAME               GPIO_SD_B1_05   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SS0_LABEL                "FLEXSPI_B_SS0"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_B_SS0_NAME                 "FLEXSPI_B_SS0"   /*!< Identifier name */

/* GPIO_SD_B1_06 (coord L3), FLEXSPI_A_SS0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SS0_PERIPHERAL                   FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SS0_SIGNAL               FLEXSPI_A_SS0_B   /*!< FLEXSPI signal: FLEXSPI_A_SS0_B */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SS0_PIN_NAME               GPIO_SD_B1_06   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SS0_LABEL                "FLEXSPI_A_SS0"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SS0_NAME                 "FLEXSPI_A_SS0"   /*!< Identifier name */

/* GPIO_SD_B1_07 (coord L4), FLEXSPI_A_SCLK */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SCLK_PERIPHERAL                  FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SCLK_SIGNAL               FLEXSPI_A_SCLK   /*!< FLEXSPI signal: FLEXSPI_A_SCLK */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SCLK_PIN_NAME              GPIO_SD_B1_07   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SCLK_LABEL              "FLEXSPI_A_SCLK"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_SCLK_NAME               "FLEXSPI_A_SCLK"   /*!< Identifier name */

/* GPIO_SD_B1_08 (coord P3), FLEXSPI_A_DATA0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA0_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA0_SIGNAL             FLEXSPI_A_DATA0   /*!< FLEXSPI signal: FLEXSPI_A_DATA0 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA0_PIN_NAME             GPIO_SD_B1_08   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA0_LABEL            "FLEXSPI_A_DATA0"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA0_NAME             "FLEXSPI_A_DATA0"   /*!< Identifier name */

/* GPIO_SD_B1_09 (coord N4), FLEXSPI_A_DATA1 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA1_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA1_SIGNAL             FLEXSPI_A_DATA1   /*!< FLEXSPI signal: FLEXSPI_A_DATA1 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA1_PIN_NAME             GPIO_SD_B1_09   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA1_LABEL            "FLEXSPI_A_DATA1"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA1_NAME             "FLEXSPI_A_DATA1"   /*!< Identifier name */

/* GPIO_SD_B1_10 (coord P4), FLEXSPI_A_DATA2 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA2_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA2_SIGNAL             FLEXSPI_A_DATA2   /*!< FLEXSPI signal: FLEXSPI_A_DATA2 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA2_PIN_NAME             GPIO_SD_B1_10   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA2_LABEL            "FLEXSPI_A_DATA2"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA2_NAME             "FLEXSPI_A_DATA2"   /*!< Identifier name */

/* GPIO_SD_B1_11 (coord P5), FLEXSPI_A_DATA3 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA3_PERIPHERAL                 FLEXSPI   /*!< Device name: FLEXSPI */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA3_SIGNAL             FLEXSPI_A_DATA3   /*!< FLEXSPI signal: FLEXSPI_A_DATA3 */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA3_PIN_NAME             GPIO_SD_B1_11   /*!< Pin name */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA3_LABEL            "FLEXSPI_A_DATA3"   /*!< Label */
#define BOARD_INITFLEXSPIPINS_FLEXSPI_A_DATA3_NAME             "FLEXSPI_A_DATA3"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexSPIPins(void);

/* GPIO_B1_12 (coord D13), USDHC1_CD_B */
#define BOARD_INITUSDHCPINS_USDHC1_CD_B_PERIPHERAL                        USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_CD_B_SIGNAL                        usdhc_cd_b   /*!< USDHC1 signal: usdhc_cd_b */
#define BOARD_INITUSDHCPINS_USDHC1_CD_B_PIN_NAME                      GPIO_B1_12   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_CD_B_LABEL                      "USDHC1_CD_B"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_CD_B_NAME                       "USDHC1_CD_B"   /*!< Identifier name */

/* GPIO_SD_B0_00 (coord J4), USDHC1_CMD */
#define BOARD_INITUSDHCPINS_USDHC1_CMD_PERIPHERAL                         USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_CMD_SIGNAL                          usdhc_cmd   /*!< USDHC1 signal: usdhc_cmd */
#define BOARD_INITUSDHCPINS_USDHC1_CMD_PIN_NAME                    GPIO_SD_B0_00   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_CMD_LABEL                        "USDHC1_CMD"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_CMD_NAME                         "USDHC1_CMD"   /*!< Identifier name */

/* GPIO_SD_B0_01 (coord J3), USDHC1_CLK */
#define BOARD_INITUSDHCPINS_USDHC1_CLK_PERIPHERAL                         USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_CLK_SIGNAL                          usdhc_clk   /*!< USDHC1 signal: usdhc_clk */
#define BOARD_INITUSDHCPINS_USDHC1_CLK_PIN_NAME                    GPIO_SD_B0_01   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_CLK_LABEL                        "USDHC1_CLK"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_CLK_NAME                         "USDHC1_CLK"   /*!< Identifier name */

/* GPIO_SD_B0_02 (coord J1), USDHC1_DATA0 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_PERIPHERAL                       USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_SIGNAL                       usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_CHANNEL                              0U   /*!< USDHC1 usdhc_data channel: 0 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_PIN_NAME                  GPIO_SD_B0_02   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_LABEL                    "USDHC1_DATA0"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_DATA0_NAME                     "USDHC1_DATA0"   /*!< Identifier name */

/* GPIO_SD_B0_03 (coord K1), USDHC1_DATA1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_PERIPHERAL                       USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_SIGNAL                       usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_CHANNEL                              1U   /*!< USDHC1 usdhc_data channel: 1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_PIN_NAME                  GPIO_SD_B0_03   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_LABEL                    "USDHC1_DATA1"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_DATA1_NAME                     "USDHC1_DATA1"   /*!< Identifier name */

/* GPIO_SD_B0_04 (coord H2), USDHC1_DATA2 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_PERIPHERAL                       USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_SIGNAL                       usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_CHANNEL                              2U   /*!< USDHC1 usdhc_data channel: 2 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_PIN_NAME                  GPIO_SD_B0_04   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_LABEL                    "USDHC1_DATA2"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_DATA2_NAME                     "USDHC1_DATA2"   /*!< Identifier name */

/* GPIO_SD_B0_05 (coord J2), USDHC1_DATA3 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_PERIPHERAL                       USDHC1   /*!< Device name: USDHC1 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_SIGNAL                       usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_CHANNEL                              3U   /*!< USDHC1 usdhc_data channel: 3 */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_PIN_NAME                  GPIO_SD_B0_05   /*!< Pin name */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_LABEL                    "USDHC1_DATA3"   /*!< Label */
#define BOARD_INITUSDHCPINS_USDHC1_DATA3_NAME                     "USDHC1_DATA3"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUsdhcPins(void);

/* GPIO_EMC_19 (coord B4), MODBUS_PROFIBUS_TX */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_TX_PERIPHERAL                 LPUART4   /*!< Device name: LPUART4 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_TX_SIGNAL                          TX   /*!< LPUART4 signal: TX */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_TX_PIN_NAME               GPIO_EMC_19   /*!< Pin name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_TX_LABEL         "MODBUS_PROFIBUS_TX"   /*!< Label */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_TX_NAME          "MODBUS_PROFIBUS_TX"   /*!< Identifier name */

/* GPIO_EMC_20 (coord A3), MODBUS_PROFIBUS_RX */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RX_PERIPHERAL                 LPUART4   /*!< Device name: LPUART4 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RX_SIGNAL                          RX   /*!< LPUART4 signal: RX */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RX_PIN_NAME               GPIO_EMC_20   /*!< Pin name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RX_LABEL         "MODBUS_PROFIBUS_RX"   /*!< Label */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RX_NAME          "MODBUS_PROFIBUS_RX"   /*!< Identifier name */

/* GPIO_AD_B0_02 (coord M11), SERIAL_TX */
#define BOARD_INITUARTPINS_SERIAL_TX_PERIPHERAL                          LPUART6   /*!< Device name: LPUART6 */
#define BOARD_INITUARTPINS_SERIAL_TX_SIGNAL                                   TX   /*!< LPUART6 signal: TX */
#define BOARD_INITUARTPINS_SERIAL_TX_PIN_NAME                      GPIO_AD_B0_02   /*!< Pin name */
#define BOARD_INITUARTPINS_SERIAL_TX_LABEL                           "SERIAL_TX"   /*!< Label */
#define BOARD_INITUARTPINS_SERIAL_TX_NAME                            "SERIAL_TX"   /*!< Identifier name */

/* GPIO_AD_B0_03 (coord G11), SERIAL_RX */
#define BOARD_INITUARTPINS_SERIAL_RX_PERIPHERAL                          LPUART6   /*!< Device name: LPUART6 */
#define BOARD_INITUARTPINS_SERIAL_RX_SIGNAL                                   RX   /*!< LPUART6 signal: RX */
#define BOARD_INITUARTPINS_SERIAL_RX_PIN_NAME                      GPIO_AD_B0_03   /*!< Pin name */
#define BOARD_INITUARTPINS_SERIAL_RX_LABEL                           "SERIAL_RX"   /*!< Label */
#define BOARD_INITUARTPINS_SERIAL_RX_NAME                            "SERIAL_RX"   /*!< Identifier name */

/* GPIO_EMC_38 (coord D6), MODBUS_PROFIBUS_DE */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_GPIO                         GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_PORT                         GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_GPIO_PIN                       24U   /*!< GPIO3 pin index: 24 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_PIN_NAME               GPIO_EMC_38   /*!< Pin name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_LABEL         "MODBUS_PROFIBUS_DE"   /*!< Label */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_NAME          "MODBUS_PROFIBUS_DE"   /*!< Identifier name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_DE_DIRECTION kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_EMC_39 (coord B7), MODBUS_PROFIBUS_RE */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_GPIO                         GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_PORT                         GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_GPIO_PIN                       25U   /*!< GPIO3 pin index: 25 */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_PIN_NAME               GPIO_EMC_39   /*!< Pin name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_LABEL         "MODBUS_PROFIBUS_RE"   /*!< Label */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_NAME          "MODBUS_PROFIBUS_RE"   /*!< Identifier name */
#define BOARD_INITUARTPINS_MODBUS_PROFIBUS_RE_DIRECTION kPIN_MUX_DirectionOutput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUartPins(void);

/* GPIO_EMC_21 (coord C1), SECURITY_SDA */
#define BOARD_INITI2CPINS_SECURITY_SDA_PERIPHERAL                         LPI2C3   /*!< Device name: LPI2C3 */
#define BOARD_INITI2CPINS_SECURITY_SDA_SIGNAL                                SDA   /*!< LPI2C3 signal: SDA */
#define BOARD_INITI2CPINS_SECURITY_SDA_PIN_NAME                      GPIO_EMC_21   /*!< Pin name */
#define BOARD_INITI2CPINS_SECURITY_SDA_LABEL                      "SECURITY_SDA"   /*!< Label */
#define BOARD_INITI2CPINS_SECURITY_SDA_NAME                       "SECURITY_SDA"   /*!< Identifier name */

/* GPIO_EMC_22 (coord F1), SECURITY_SCL */
#define BOARD_INITI2CPINS_SECURITY_SCL_PERIPHERAL                         LPI2C3   /*!< Device name: LPI2C3 */
#define BOARD_INITI2CPINS_SECURITY_SCL_SIGNAL                                SCL   /*!< LPI2C3 signal: SCL */
#define BOARD_INITI2CPINS_SECURITY_SCL_PIN_NAME                      GPIO_EMC_22   /*!< Pin name */
#define BOARD_INITI2CPINS_SECURITY_SCL_LABEL                      "SECURITY_SCL"   /*!< Label */
#define BOARD_INITI2CPINS_SECURITY_SCL_NAME                       "SECURITY_SCL"   /*!< Identifier name */

/* GPIO_EMC_11 (coord G3), LCD_TOUCH_SDA */
#define BOARD_INITI2CPINS_LCD_TOUCH_SDA_PERIPHERAL                        LPI2C4   /*!< Device name: LPI2C4 */
#define BOARD_INITI2CPINS_LCD_TOUCH_SDA_SIGNAL                               SDA   /*!< LPI2C4 signal: SDA */
#define BOARD_INITI2CPINS_LCD_TOUCH_SDA_PIN_NAME                     GPIO_EMC_11   /*!< Pin name */
#define BOARD_INITI2CPINS_LCD_TOUCH_SDA_LABEL                    "LCD_TOUCH_SDA"   /*!< Label */
#define BOARD_INITI2CPINS_LCD_TOUCH_SDA_NAME                     "LCD_TOUCH_SDA"   /*!< Identifier name */

/* GPIO_EMC_12 (coord H1), LCD_TOUCH_SCL */
#define BOARD_INITI2CPINS_LCD_TOUCH_SCL_PERIPHERAL                        LPI2C4   /*!< Device name: LPI2C4 */
#define BOARD_INITI2CPINS_LCD_TOUCH_SCL_SIGNAL                               SCL   /*!< LPI2C4 signal: SCL */
#define BOARD_INITI2CPINS_LCD_TOUCH_SCL_PIN_NAME                     GPIO_EMC_12   /*!< Pin name */
#define BOARD_INITI2CPINS_LCD_TOUCH_SCL_LABEL                    "LCD_TOUCH_SCL"   /*!< Label */
#define BOARD_INITI2CPINS_LCD_TOUCH_SCL_NAME                     "LCD_TOUCH_SCL"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2cPins(void);

/* GPIO_AD_B0_06 (coord E14), SWD_DIO */
#define BOARD_INITSWDPINS_SWD_DIO_PERIPHERAL                                JTAG   /*!< Device name: JTAG */
#define BOARD_INITSWDPINS_SWD_DIO_SIGNAL                                     TMS   /*!< JTAG signal: TMS */
#define BOARD_INITSWDPINS_SWD_DIO_PIN_NAME                         GPIO_AD_B0_06   /*!< Pin name */
#define BOARD_INITSWDPINS_SWD_DIO_LABEL                                "SWD_DIO"   /*!< Label */
#define BOARD_INITSWDPINS_SWD_DIO_NAME                                 "SWD_DIO"   /*!< Identifier name */

/* GPIO_AD_B0_07 (coord F12), SWD_CLK */
#define BOARD_INITSWDPINS_SWD_CLK_PERIPHERAL                                JTAG   /*!< Device name: JTAG */
#define BOARD_INITSWDPINS_SWD_CLK_SIGNAL                                     TCK   /*!< JTAG signal: TCK */
#define BOARD_INITSWDPINS_SWD_CLK_PIN_NAME                         GPIO_AD_B0_07   /*!< Pin name */
#define BOARD_INITSWDPINS_SWD_CLK_LABEL                                "SWD_CLK"   /*!< Label */
#define BOARD_INITSWDPINS_SWD_CLK_NAME                                 "SWD_CLK"   /*!< Identifier name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSwdPins(void);

/* GPIO_AD_B0_04 (coord F11), USER_BUTTON1 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_GPIO                         GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_PORT                         GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_GPIO_PIN                        4U   /*!< GPIO1 pin index: 4 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_PIN_NAME             GPIO_AD_B0_04   /*!< Pin name */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_LABEL               "USER_BUTTON1"   /*!< Label */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_NAME                "USER_BUTTON1"   /*!< Identifier name */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON1_DIRECTION  kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_AD_B0_05 (coord G14), USER_BUTTON2 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_GPIO                         GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_PORT                         GPIO1   /*!< PORT device name: GPIO1 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_GPIO_PIN                        5U   /*!< GPIO1 pin index: 5 */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_PIN_NAME             GPIO_AD_B0_05   /*!< Pin name */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_LABEL               "USER_BUTTON2"   /*!< Label */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_NAME                "USER_BUTTON2"   /*!< Identifier name */
#define BOARD_INITUSERBUTTONPINS_USER_BUTTON2_DIRECTION  kPIN_MUX_DirectionInput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUserButtonPins(void);

/* GPIO_B0_13 (coord D10), USER_LED1 */
#define BOARD_INITUSERLEDPINS_USER_LED1_GPIO                               GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITUSERLEDPINS_USER_LED1_PORT                               GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITUSERLEDPINS_USER_LED1_GPIO_PIN                             13U   /*!< GPIO2 pin index: 13 */
#define BOARD_INITUSERLEDPINS_USER_LED1_PIN_NAME                      GPIO_B0_13   /*!< Pin name */
#define BOARD_INITUSERLEDPINS_USER_LED1_LABEL                        "USER_LED1"   /*!< Label */
#define BOARD_INITUSERLEDPINS_USER_LED1_NAME                         "USER_LED1"   /*!< Identifier name */
#define BOARD_INITUSERLEDPINS_USER_LED1_DIRECTION       kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_B0_14 (coord E10), USER_LED2 */
#define BOARD_INITUSERLEDPINS_USER_LED2_GPIO                               GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITUSERLEDPINS_USER_LED2_PORT                               GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITUSERLEDPINS_USER_LED2_GPIO_PIN                             14U   /*!< GPIO2 pin index: 14 */
#define BOARD_INITUSERLEDPINS_USER_LED2_PIN_NAME                      GPIO_B0_14   /*!< Pin name */
#define BOARD_INITUSERLEDPINS_USER_LED2_LABEL                        "USER_LED2"   /*!< Label */
#define BOARD_INITUSERLEDPINS_USER_LED2_NAME                         "USER_LED2"   /*!< Identifier name */
#define BOARD_INITUSERLEDPINS_USER_LED2_DIRECTION       kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_EMC_41 (coord C7), USER_LED4 */
#define BOARD_INITUSERLEDPINS_USER_LED4_GPIO                               GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITUSERLEDPINS_USER_LED4_PORT                               GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITUSERLEDPINS_USER_LED4_GPIO_PIN                             27U   /*!< GPIO3 pin index: 27 */
#define BOARD_INITUSERLEDPINS_USER_LED4_PIN_NAME                     GPIO_EMC_41   /*!< Pin name */
#define BOARD_INITUSERLEDPINS_USER_LED4_LABEL                        "USER_LED4"   /*!< Label */
#define BOARD_INITUSERLEDPINS_USER_LED4_NAME                         "USER_LED4"   /*!< Identifier name */

/* GPIO_EMC_10 (coord G1), USER_LED3 */
#define BOARD_INITUSERLEDPINS_USER_LED3_GPIO                               GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITUSERLEDPINS_USER_LED3_PORT                               GPIO4   /*!< PORT device name: GPIO4 */
#define BOARD_INITUSERLEDPINS_USER_LED3_GPIO_PIN                             10U   /*!< GPIO4 pin index: 10 */
#define BOARD_INITUSERLEDPINS_USER_LED3_PIN_NAME                     GPIO_EMC_10   /*!< Pin name */
#define BOARD_INITUSERLEDPINS_USER_LED3_LABEL                        "USER_LED3"   /*!< Label */
#define BOARD_INITUSERLEDPINS_USER_LED3_NAME                         "USER_LED3"   /*!< Identifier name */
#define BOARD_INITUSERLEDPINS_USER_LED3_DIRECTION       kPIN_MUX_DirectionOutput   /*!< Direction */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUserLedPins(void);

/* GPIO_B0_12 (coord C10), PERI_PWDN */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_GPIO                            GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_PORT                            GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_GPIO_PIN                          12U   /*!< GPIO2 pin index: 12 */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_PIN_NAME                   GPIO_B0_12   /*!< Pin name */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_LABEL                     "PERI_PWDN"   /*!< Label */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_NAME                      "PERI_PWDN"   /*!< Identifier name */
#define BOARD_INITADDITIONALPINS_PERI_PWDN_DIRECTION    kPIN_MUX_DirectionOutput   /*!< Direction */

/* PMIC_STBY_REQ (coord L7), PERI_PWR_ENABLE */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_GPIO                      GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_PORT                      GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_GPIO_PIN                     2U   /*!< GPIO5 pin index: 2 */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_PIN_NAME          PMIC_STBY_REQ   /*!< Pin name */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_LABEL         "PERI_PWR_ENABLE"   /*!< Label */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_NAME          "PERI_PWR_ENABLE"   /*!< Identifier name */
#define BOARD_INITADDITIONALPINS_PERI_PWR_ENABLE_DIRECTION kPIN_MUX_DirectionOutput /*!< Direction */

/* WAKEUP (coord L6), WAKEUP */
#define BOARD_INITADDITIONALPINS_WAKEUP_GPIO                               GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_WAKEUP_PORT                               GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_WAKEUP_GPIO_PIN                              0U   /*!< GPIO5 pin index: 0 */
#define BOARD_INITADDITIONALPINS_WAKEUP_PIN_NAME                          WAKEUP   /*!< Pin name */
#define BOARD_INITADDITIONALPINS_WAKEUP_LABEL                           "WAKEUP"   /*!< Label */
#define BOARD_INITADDITIONALPINS_WAKEUP_NAME                            "WAKEUP"   /*!< Identifier name */

/* GPIO_B1_13 (coord D14), WDOG1_B */
#define BOARD_INITADDITIONALPINS_WDOG1_B_PERIPHERAL                        WDOG1   /*!< Device name: WDOG1 */
#define BOARD_INITADDITIONALPINS_WDOG1_B_SIGNAL                           wdog_b   /*!< WDOG1 signal: wdog_b */
#define BOARD_INITADDITIONALPINS_WDOG1_B_PIN_NAME                     GPIO_B1_13   /*!< Pin name */
#define BOARD_INITADDITIONALPINS_WDOG1_B_LABEL                         "WDOG1_B"   /*!< Label */
#define BOARD_INITADDITIONALPINS_WDOG1_B_NAME                          "WDOG1_B"   /*!< Identifier name */

/* PMIC_ON_REQ (coord K7), PMIC_ON_REQ */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_GPIO                          GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_PORT                          GPIO5   /*!< PORT device name: GPIO5 */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_GPIO_PIN                         1U   /*!< GPIO5 pin index: 1 */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_PIN_NAME                PMIC_ON_REQ   /*!< Pin name */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_LABEL                 "PMIC_ON_REQ"   /*!< Label */
#define BOARD_INITADDITIONALPINS_PMIC_ON_REQ_NAME                  "PMIC_ON_REQ"   /*!< Identifier name */


/* GPIO_B0_08 (coord G11), NFC_IRQ */
#define BOARD_INITPINS_NFC_IRQ_GPIO                                        GPIO2   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NFC_IRQ_PORT                                        GPIO2   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NFC_IRQ_GPIO_PIN                                       8U   /*!< GPIO1 pin index: 3 */
#define BOARD_INITPINS_NFC_IRQ_PIN_NAME                               GPIO_B0_08   /*!< Pin name */
#define BOARD_INITPINS_NFC_IRQ_LABEL                                   "NFC_IRQ"   /*!< Label */
#define BOARD_INITPINS_NFC_IRQ_NAME                                    "NFC_IRQ"   /*!< Identifier name */
#define BOARD_INITPINS_NFC_IRQ_DIRECTION                 kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_B0_09 (coord M12), NFC_VEN */
#define BOARD_INITPINS_NFC_VEN_GPIO                                        GPIO2   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_NFC_VEN_PORT                                        GPIO2   /*!< PORT device name: GPIO1 */
#define BOARD_INITPINS_NFC_VEN_GPIO_PIN                                       9U   /*!< GPIO1 pin index: 19 */
#define BOARD_INITPINS_NFC_VEN_PIN_NAME                               GPIO_B0_09   /*!< Pin name */
#define BOARD_INITPINS_NFC_VEN_LABEL                                   "NFC_VEN"   /*!< Label */
#define BOARD_INITPINS_NFC_VEN_NAME                                    "NFC_VEN"   /*!< Identifier name */
#define BOARD_INITPINS_NFC_VEN_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitAdditionalPins(void);

/*!
 * @brief Reonfigures LCD pins to I2C (NCF based) pins.
 *
 */
void BOARD_InitNfcPins(void);

/*!
 * @brief Reonfigures I2C (NCF based)to LCD pins pins.
 *
 */
void BOARD_DeinitNfcPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
