/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MIMXRT1052xxxxx
package_id: MIMXRT1052DVL6A
mcu_data: ksdk2_0
processor_version: 3.0.2
pin_labels:
- {pin_num: M14, pin_signal: GPIO_AD_B0_00, label: PWM2_CT, identifier: PWM2_CT}
- {pin_num: H10, pin_signal: GPIO_AD_B0_01, label: PWM2_CB, identifier: PWM2_CB}
- {pin_num: M11, pin_signal: GPIO_AD_B0_02, label: SERIAL_TX, identifier: SERIAL_TX}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: SERIAL_RX, identifier: SERIAL_RX}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: USER_BUTTON1, identifier: USER_BUTTON1}
- {pin_num: G14, pin_signal: GPIO_AD_B0_05, label: USER_BUTTON2, identifier: USER_BUTTON2}
- {pin_num: E14, pin_signal: GPIO_AD_B0_06, label: SWD_DIO, identifier: SWD_DIO}
- {pin_num: F12, pin_signal: GPIO_AD_B0_07, label: SWD_CLK, identifier: SWD_CLK}
- {pin_num: F13, pin_signal: GPIO_AD_B0_08, label: LCD_BACKLIGHT_CTRL, identifier: LCD_BACKLIGHT_CTRL}
- {pin_num: F14, pin_signal: GPIO_AD_B0_09, label: ENET_RST, identifier: ENET_RST}
- {pin_num: G13, pin_signal: GPIO_AD_B0_10, label: ENET_INT, identifier: ENET_INT}
- {pin_num: G10, pin_signal: GPIO_AD_B0_11, label: LCD_TOUCH_INT, identifier: LCD_TOUCH_INT}
- {pin_num: K14, pin_signal: GPIO_AD_B0_12, label: CURR1_DCB, identifier: CURR1_DCB}
- {pin_num: L14, pin_signal: GPIO_AD_B0_13, label: VOLT1_DCB, identifier: VOLT1_DCB}
- {pin_num: H14, pin_signal: GPIO_AD_B0_14, label: CURR2_DCB, identifier: CURR2_DCB}
- {pin_num: L10, pin_signal: GPIO_AD_B0_15, label: VOLT2_DCB, identifier: VOLT2_DCB}
- {pin_num: J11, pin_signal: GPIO_AD_B1_00, label: CURR1_A, identifier: CURR1_A}
- {pin_num: K11, pin_signal: GPIO_AD_B1_01, label: CURR1_B, identifier: CURR1_B}
- {pin_num: L11, pin_signal: GPIO_AD_B1_02, label: CURR1_C, identifier: CURR1_C}
- {pin_num: M12, pin_signal: GPIO_AD_B1_03, label: CURR2_A, identifier: CURR2_A}
- {pin_num: L12, pin_signal: GPIO_AD_B1_04, label: CURR2_B, identifier: CURR2_B}
- {pin_num: K12, pin_signal: GPIO_AD_B1_05, label: CURR2_C, identifier: CURR2_C}
- {pin_num: J12, pin_signal: GPIO_AD_B1_06, label: CURR3_A, identifier: CURR3_A}
- {pin_num: K10, pin_signal: GPIO_AD_B1_07, label: CURR3_B, identifier: CURR3_B}
- {pin_num: H13, pin_signal: GPIO_AD_B1_08, label: CURR3_C, identifier: CURR3_C}
- {pin_num: M13, pin_signal: GPIO_AD_B1_09, label: CURR4_A, identifier: CURR4_A}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: CURR4_B, identifier: CURR4_B}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: CURR4_C, identifier: CURR4_C}
- {pin_num: H12, pin_signal: GPIO_AD_B1_12, label: CURR3_DCB, identifier: CURR3_DCB}
- {pin_num: H11, pin_signal: GPIO_AD_B1_13, label: VOLT3_DCB, identifier: VOLT3_DCB}
- {pin_num: G12, pin_signal: GPIO_AD_B1_14, label: CURR4_DCB, identifier: CURR4_DCB}
- {pin_num: J14, pin_signal: GPIO_AD_B1_15, label: VOLT4_DCB, identifier: VOLT4_DCB}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: LCDIF_CLK, identifier: LCDIF_CLK}
- {pin_num: E7, pin_signal: GPIO_B0_01, label: LCDIF_ENABLE, identifier: LCDIF_ENABLE}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: LCDIF_HSYNC, identifier: LCDIF_HSYNC}
- {pin_num: D8, pin_signal: GPIO_B0_03, label: LCDIF_VSYNC, identifier: LCDIF_VSYNC}
- {pin_num: C8, pin_signal: GPIO_B0_04, label: LCDIF_DATA00, identifier: LCDIF_DATA00}
- {pin_num: B8, pin_signal: GPIO_B0_05, label: LCDIF_DATA01, identifier: LCDIF_DATA01}
- {pin_num: A8, pin_signal: GPIO_B0_06, label: LCDIF_DATA02, identifier: LCDIF_DATA02}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: LCDIF_DATA03, identifier: LCDIF_DATA03}
- {pin_num: B9, pin_signal: GPIO_B0_08, label: LCDIF_DATA04, identifier: LCDIF_DATA04}
- {pin_num: C9, pin_signal: GPIO_B0_09, label: LCDIF_DATA05, identifier: LCDIF_DATA05}
- {pin_num: D9, pin_signal: GPIO_B0_10, label: LCDIF_DATA06, identifier: LCDIF_DATA06}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: LCDIF_DATA07, identifier: LCDIF_DATA07}
- {pin_num: C10, pin_signal: GPIO_B0_12, label: PERI_PWDN, identifier: PERI_PWDN}
- {pin_num: D10, pin_signal: GPIO_B0_13, label: USER_LED1, identifier: USER_LED1}
- {pin_num: E10, pin_signal: GPIO_B0_14, label: USER_LED2, identifier: USER_LED2}
- {pin_num: E11, pin_signal: GPIO_B0_15, label: ENC2_I, identifier: ENC2_I}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: ENC3_I, identifier: ENC3_I}
- {pin_num: B11, pin_signal: GPIO_B1_01, label: ENC4_A, identifier: ENC4_A}
- {pin_num: C11, pin_signal: GPIO_B1_02, label: ENC4_B, identifier: ENC4_B}
- {pin_num: D11, pin_signal: GPIO_B1_03, label: ENC4_I, identifier: ENC4_I}
- {pin_num: E12, pin_signal: GPIO_B1_04, label: ENET_RX_DATA0, identifier: ENET_RX_DATA0}
- {pin_num: D12, pin_signal: GPIO_B1_05, label: ENET_RX_DATA1, identifier: ENET_RX_DATA1}
- {pin_num: C12, pin_signal: GPIO_B1_06, label: ENET_CRS_RV, identifier: ENET_CRS_RV}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: ENET_TX_DATA0, identifier: ENET_TX_DATA0}
- {pin_num: A12, pin_signal: GPIO_B1_08, label: ENET_TX_DATA1, identifier: ENET_TX_DATA1}
- {pin_num: A13, pin_signal: GPIO_B1_09, label: ENET_TX_EN, identifier: ENET_TX_EN}
- {pin_num: B13, pin_signal: GPIO_B1_10, label: ENET_TX_CLK, identifier: ENET_TX_CLK}
- {pin_num: C13, pin_signal: GPIO_B1_11, label: ENET_RX_ER, identifier: ENET_RX_ER}
- {pin_num: D13, pin_signal: GPIO_B1_12, label: USDHC1_CD_B, identifier: USDHC1_CD_B}
- {pin_num: D14, pin_signal: GPIO_B1_13, label: WDOG1_B, identifier: WDOG1_B}
- {pin_num: C14, pin_signal: GPIO_B1_14, label: ENET_MDC, identifier: ENET_MDC}
- {pin_num: B14, pin_signal: GPIO_B1_15, label: ENET_MDIO, identifier: ENET_MDIO}
- {pin_num: E3, pin_signal: GPIO_EMC_00, label: PWM4_AT, identifier: PWM4_AT}
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: PWM4_AB, identifier: PWM4_AB}
- {pin_num: F4, pin_signal: GPIO_EMC_02, label: PWM4_BT, identifier: PWM4_BT}
- {pin_num: G4, pin_signal: GPIO_EMC_03, label: PWM4_BB, identifier: PWM4_BB}
- {pin_num: F2, pin_signal: GPIO_EMC_04, label: PWM4_CT, identifier: PWM4_CT}
- {pin_num: G5, pin_signal: GPIO_EMC_05, label: PWM4_CB, identifier: PWM4_CB}
- {pin_num: H5, pin_signal: GPIO_EMC_06, label: PWM2_AT, identifier: PWM2_AT}
- {pin_num: H4, pin_signal: GPIO_EMC_07, label: PWM2_AB, identifier: PWM2_AB}
- {pin_num: H3, pin_signal: GPIO_EMC_08, label: PWM2_BT, identifier: PWM2_BT}
- {pin_num: C2, pin_signal: GPIO_EMC_09, label: PWM2_BB, identifier: PWM2_BB}
- {pin_num: G1, pin_signal: GPIO_EMC_10, label: USER_LED3, identifier: USER_LED3}
- {pin_num: G3, pin_signal: GPIO_EMC_11, label: LCD_TOUCH_SDA, identifier: LCD_TOUCH_SDA}
- {pin_num: H1, pin_signal: GPIO_EMC_12, label: LCD_TOUCH_SCL, identifier: LCD_TOUCH_SCL}
- {pin_num: A6, pin_signal: GPIO_EMC_13, label: ENC2_A, identifier: ENC2_A}
- {pin_num: B6, pin_signal: GPIO_EMC_14, label: ENC2_B, identifier: ENC2_B}
- {pin_num: B1, pin_signal: GPIO_EMC_15, label: ENC3_A, identifier: ENC3_A}
- {pin_num: A5, pin_signal: GPIO_EMC_16, label: ENC3_B, identifier: ENC3_B}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: FLEXCAN1_TX, identifier: FLEXCAN1_TX}
- {pin_num: B2, pin_signal: GPIO_EMC_18, label: FLEXCAN1_RX, identifier: FLEXCAN1_RX}
- {pin_num: B4, pin_signal: GPIO_EMC_19, label: MODBUS_PROFIBUS_TX, identifier: MODBUS_PROFIBUS_TX}
- {pin_num: A3, pin_signal: GPIO_EMC_20, label: MODBUS_PROFIBUS_RX, identifier: MODBUS_PROFIBUS_RX}
- {pin_num: C1, pin_signal: GPIO_EMC_21, label: SECURITY_SDA, identifier: SECURITY_SDA}
- {pin_num: F1, pin_signal: GPIO_EMC_22, label: SECURITY_SCL, identifier: SECURITY_SCL}
- {pin_num: G2, pin_signal: GPIO_EMC_23, label: PWM1_AT, identifier: PWM1_AT}
- {pin_num: D3, pin_signal: GPIO_EMC_24, label: PWM1_AB, identifier: PWM1_AB}
- {pin_num: D2, pin_signal: GPIO_EMC_25, label: PWM1_BT, identifier: PWM1_BT}
- {pin_num: B3, pin_signal: GPIO_EMC_26, label: PWM1_BB, identifier: PWM1_BB}
- {pin_num: A2, pin_signal: GPIO_EMC_27, label: PWM1_CT, identifier: PWM1_CT}
- {pin_num: D1, pin_signal: GPIO_EMC_28, label: PWM1_CB, identifier: PWM1_CB}
- {pin_num: E1, pin_signal: GPIO_EMC_29, label: PWM3_AT, identifier: PWM3_AT}
- {pin_num: C6, pin_signal: GPIO_EMC_30, label: PWM3_AB, identifier: PWM3_AB}
- {pin_num: C5, pin_signal: GPIO_EMC_31, label: PWM3_BT, identifier: PWM3_BT}
- {pin_num: D5, pin_signal: GPIO_EMC_32, label: PWM3_BB, identifier: PWM3_BB}
- {pin_num: C4, pin_signal: GPIO_EMC_33, label: PWM3_CT, identifier: PWM3_CT}
- {pin_num: D4, pin_signal: GPIO_EMC_34, label: PWM3_CB, identifier: PWM3_CB}
- {pin_num: E5, pin_signal: GPIO_EMC_35, label: ENC1_A, identifier: ENC1_A}
- {pin_num: C3, pin_signal: GPIO_EMC_36, label: ENC1_B, identifier: ENC1_B}
- {pin_num: E4, pin_signal: GPIO_EMC_37, label: ENC1_I, identifier: ENC1_I}
- {pin_num: D6, pin_signal: GPIO_EMC_38, label: MODBUS_PROFIBUS_DE, identifier: MODBUS_PROFIBUS_DE}
- {pin_num: B7, pin_signal: GPIO_EMC_39, label: MODBUS_PROFIBUS_RE, identifier: MODBUS_PROFIBUS_RE}
- {pin_num: A7, pin_signal: GPIO_EMC_40, label: LCD_RST, identifier: LCD_RST}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: USER_LED4, identifier: USER_LED4}
- {pin_num: J4, pin_signal: GPIO_SD_B0_00, label: USDHC1_CMD, identifier: USDHC1_CMD}
- {pin_num: J3, pin_signal: GPIO_SD_B0_01, label: USDHC1_CLK, identifier: USDHC1_CLK}
- {pin_num: J1, pin_signal: GPIO_SD_B0_02, label: USDHC1_DATA0, identifier: USDHC1_DATA0}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: USDHC1_DATA1, identifier: USDHC1_DATA1}
- {pin_num: H2, pin_signal: GPIO_SD_B0_04, label: USDHC1_DATA2, identifier: USDHC1_DATA2}
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: USDHC1_DATA3, identifier: USDHC1_DATA3}
- {pin_num: L5, pin_signal: GPIO_SD_B1_00, label: FLEXSPI_B_DATA3, identifier: FLEXSPI_B_DATA3}
- {pin_num: M5, pin_signal: GPIO_SD_B1_01, label: FLEXSPI_B_DATA2, identifier: FLEXSPI_B_DATA2}
- {pin_num: M3, pin_signal: GPIO_SD_B1_02, label: FLEXSPI_B_DATA1, identifier: FLEXSPI_B_DATA1}
- {pin_num: M4, pin_signal: GPIO_SD_B1_03, label: FLEXSPI_B_DATA0, identifier: FLEXSPI_B_DATA0}
- {pin_num: P2, pin_signal: GPIO_SD_B1_04, label: FLEXSPI_B_SCLK, identifier: FLEXSPI_B_SCLK}
- {pin_num: N3, pin_signal: GPIO_SD_B1_05, label: FLEXSPI_B_SS0, identifier: FLEXSPI_B_SS0}
- {pin_num: L3, pin_signal: GPIO_SD_B1_06, label: FLEXSPI_A_SS0, identifier: FLEXSPI_A_SS0}
- {pin_num: L4, pin_signal: GPIO_SD_B1_07, label: FLEXSPI_A_SCLK, identifier: FLEXSPI_A_SCLK}
- {pin_num: P3, pin_signal: GPIO_SD_B1_08, label: FLEXSPI_A_DATA0, identifier: FLEXSPI_A_DATA0}
- {pin_num: N4, pin_signal: GPIO_SD_B1_09, label: FLEXSPI_A_DATA1, identifier: FLEXSPI_A_DATA1}
- {pin_num: P4, pin_signal: GPIO_SD_B1_10, label: FLEXSPI_A_DATA2, identifier: FLEXSPI_A_DATA2}
- {pin_num: P5, pin_signal: GPIO_SD_B1_11, label: FLEXSPI_A_DATA3, identifier: FLEXSPI_A_DATA3}
- {pin_num: L7, pin_signal: PMIC_STBY_REQ, label: PERI_PWR_ENABLE, identifier: PERI_PWR_ENABLE}
- {pin_num: K7, pin_signal: PMIC_ON_REQ, label: PMIC_ON_REQ, identifier: PMIC_ON_REQ}
- {pin_num: L6, pin_signal: WAKEUP, label: WAKEUP, identifier: WAKEUP}
power_domains: {NVCC_EMC: '3.3', NVCC_GPIO: '3.3', VDD_SOC_IN: '1.25', NVCC_SD0: '3.3', DCDC_PSWITCH: '3.3', VDD_SNVS_IN: '3.3', VDD_USB_CAP: '5.0', DCDC_IN: '3.3',
  NVCC_SD1: '1.8', VDD_SNVS_CAP: '3.3', VDDA_ADC_3P3: '3.3', VDD_HIGH_CAP: '3.3', NVCC_PLL: '3.3', VDD_HIGH_IN: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    //BOARD_InitPins();
    BOARD_InitAdcPins();
    BOARD_InitPwmPins();
    BOARD_InitEncPins();
    BOARD_InitLcdPins();
    BOARD_InitCanPins();
    BOARD_InitEnetPins();
    //BOARD_InitFlexSPIPins();
    BOARD_InitUsdhcPins();
    BOARD_InitUartPins();
    BOARD_InitI2cPins();
    //BOARD_InitSwdPins();
    BOARD_InitUserButtonPins();
    BOARD_InitUserLedPins();
    //BOARD_InitAdditionalPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitAdcPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: K14, peripheral: ADC1, signal: 'IN, 1', pin_signal: GPIO_AD_B0_12}
  - {pin_num: L14, peripheral: ADC1, signal: 'IN, 2', pin_signal: GPIO_AD_B0_13}
  - {pin_num: H14, peripheral: ADC1, signal: 'IN, 3', pin_signal: GPIO_AD_B0_14}
  - {pin_num: L10, peripheral: ADC1, signal: 'IN, 4', pin_signal: GPIO_AD_B0_15}
  - {pin_num: J11, peripheral: ADC1, signal: 'IN, 5', pin_signal: GPIO_AD_B1_00}
  - {pin_num: K11, peripheral: ADC1, signal: 'IN, 6', pin_signal: GPIO_AD_B1_01}
  - {pin_num: L11, peripheral: ADC1, signal: 'IN, 7', pin_signal: GPIO_AD_B1_02}
  - {pin_num: M12, peripheral: ADC1, signal: 'IN, 8', pin_signal: GPIO_AD_B1_03}
  - {pin_num: L12, peripheral: ADC1, signal: 'IN, 9', pin_signal: GPIO_AD_B1_04}
  - {pin_num: K12, peripheral: ADC1, signal: 'IN, 10', pin_signal: GPIO_AD_B1_05}
  - {pin_num: J12, peripheral: ADC1, signal: 'IN, 11', pin_signal: GPIO_AD_B1_06}
  - {pin_num: K10, peripheral: ADC1, signal: 'IN, 12', pin_signal: GPIO_AD_B1_07}
  - {pin_num: H13, peripheral: ADC1, signal: 'IN, 13', pin_signal: GPIO_AD_B1_08}
  - {pin_num: M13, peripheral: ADC1, signal: 'IN, 14', pin_signal: GPIO_AD_B1_09}
  - {pin_num: L13, peripheral: ADC1, signal: 'IN, 15', pin_signal: GPIO_AD_B1_10}
  - {pin_num: J13, peripheral: ADC1, signal: 'IN, 0', pin_signal: GPIO_AD_B1_11}
  - {pin_num: H12, peripheral: ADC2, signal: 'IN, 1', pin_signal: GPIO_AD_B1_12}
  - {pin_num: H11, peripheral: ADC2, signal: 'IN, 2', pin_signal: GPIO_AD_B1_13}
  - {pin_num: G12, peripheral: ADC2, signal: 'IN, 3', pin_signal: GPIO_AD_B1_14}
  - {pin_num: J14, peripheral: ADC2, signal: 'IN, 4', pin_signal: GPIO_AD_B1_15}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitAdcPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitAdcPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_12_GPIO1_IO12,        /* GPIO_AD_B0_12 is configured as GPIO1_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_13_GPIO1_IO13,        /* GPIO_AD_B0_13 is configured as GPIO1_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_14_GPIO1_IO14,        /* GPIO_AD_B0_14 is configured as GPIO1_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_15_GPIO1_IO15,        /* GPIO_AD_B0_15 is configured as GPIO1_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_00_GPIO1_IO16,        /* GPIO_AD_B1_00 is configured as GPIO1_IO16 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_01_GPIO1_IO17,        /* GPIO_AD_B1_01 is configured as GPIO1_IO17 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_02_GPIO1_IO18,        /* GPIO_AD_B1_02 is configured as GPIO1_IO18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_03_GPIO1_IO19,        /* GPIO_AD_B1_03 is configured as GPIO1_IO19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_04_GPIO1_IO20,        /* GPIO_AD_B1_04 is configured as GPIO1_IO20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_05_GPIO1_IO21,        /* GPIO_AD_B1_05 is configured as GPIO1_IO21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_06_GPIO1_IO22,        /* GPIO_AD_B1_06 is configured as GPIO1_IO22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_07_GPIO1_IO23,        /* GPIO_AD_B1_07 is configured as GPIO1_IO23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_08_GPIO1_IO24,        /* GPIO_AD_B1_08 is configured as GPIO1_IO24 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_09_GPIO1_IO25,        /* GPIO_AD_B1_09 is configured as GPIO1_IO25 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_10_GPIO1_IO26,        /* GPIO_AD_B1_10 is configured as GPIO1_IO26 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_11_GPIO1_IO27,        /* GPIO_AD_B1_11 is configured as GPIO1_IO27 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_12_GPIO1_IO28,        /* GPIO_AD_B1_12 is configured as GPIO1_IO28 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_13_GPIO1_IO29,        /* GPIO_AD_B1_13 is configured as GPIO1_IO29 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_14_GPIO1_IO30,        /* GPIO_AD_B1_14 is configured as GPIO1_IO30 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_15_GPIO1_IO31,        /* GPIO_AD_B1_15 is configured as GPIO1_IO31 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPwmPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: G2, peripheral: PWM1, signal: 'A, 0', pin_signal: GPIO_EMC_23}
  - {pin_num: D3, peripheral: PWM1, signal: 'B, 0', pin_signal: GPIO_EMC_24}
  - {pin_num: D2, peripheral: PWM1, signal: 'A, 1', pin_signal: GPIO_EMC_25}
  - {pin_num: B3, peripheral: PWM1, signal: 'B, 1', pin_signal: GPIO_EMC_26}
  - {pin_num: A2, peripheral: PWM1, signal: 'A, 2', pin_signal: GPIO_EMC_27}
  - {pin_num: D1, peripheral: PWM1, signal: 'B, 2', pin_signal: GPIO_EMC_28}
  - {pin_num: H5, peripheral: PWM2, signal: 'A, 0', pin_signal: GPIO_EMC_06}
  - {pin_num: H4, peripheral: PWM2, signal: 'B, 0', pin_signal: GPIO_EMC_07}
  - {pin_num: H3, peripheral: PWM2, signal: 'A, 1', pin_signal: GPIO_EMC_08}
  - {pin_num: C2, peripheral: PWM2, signal: 'B, 1', pin_signal: GPIO_EMC_09}
  - {pin_num: M14, peripheral: PWM2, signal: 'A, 3', pin_signal: GPIO_AD_B0_00}
  - {pin_num: H10, peripheral: PWM2, signal: 'B, 3', pin_signal: GPIO_AD_B0_01}
  - {pin_num: E1, peripheral: PWM3, signal: 'A, 0', pin_signal: GPIO_EMC_29}
  - {pin_num: C6, peripheral: PWM3, signal: 'B, 0', pin_signal: GPIO_EMC_30}
  - {pin_num: C5, peripheral: PWM3, signal: 'A, 1', pin_signal: GPIO_EMC_31}
  - {pin_num: D5, peripheral: PWM3, signal: 'B, 1', pin_signal: GPIO_EMC_32}
  - {pin_num: C4, peripheral: PWM3, signal: 'A, 2', pin_signal: GPIO_EMC_33}
  - {pin_num: D4, peripheral: PWM3, signal: 'B, 2', pin_signal: GPIO_EMC_34}
  - {pin_num: E3, peripheral: PWM4, signal: 'A, 0', pin_signal: GPIO_EMC_00}
  - {pin_num: F3, peripheral: PWM4, signal: 'B, 0', pin_signal: GPIO_EMC_01}
  - {pin_num: F4, peripheral: PWM4, signal: 'A, 1', pin_signal: GPIO_EMC_02}
  - {pin_num: G4, peripheral: PWM4, signal: 'B, 1', pin_signal: GPIO_EMC_03}
  - {pin_num: F2, peripheral: PWM4, signal: 'A, 2', pin_signal: GPIO_EMC_04}
  - {pin_num: G5, peripheral: PWM4, signal: 'B, 2', pin_signal: GPIO_EMC_05}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPwmPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPwmPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_00_FLEXPWM2_PWMA03,   /* GPIO_AD_B0_00 is configured as FLEXPWM2_PWMA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_01_FLEXPWM2_PWMB03,   /* GPIO_AD_B0_01 is configured as FLEXPWM2_PWMB03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_00_FLEXPWM4_PWMA00,     /* GPIO_EMC_00 is configured as FLEXPWM4_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_01_FLEXPWM4_PWMB00,     /* GPIO_EMC_01 is configured as FLEXPWM4_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_02_FLEXPWM4_PWMA01,     /* GPIO_EMC_02 is configured as FLEXPWM4_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_03_FLEXPWM4_PWMB01,     /* GPIO_EMC_03 is configured as FLEXPWM4_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_04_FLEXPWM4_PWMA02,     /* GPIO_EMC_04 is configured as FLEXPWM4_PWMA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_05_FLEXPWM4_PWMB02,     /* GPIO_EMC_05 is configured as FLEXPWM4_PWMB02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_06_FLEXPWM2_PWMA00,     /* GPIO_EMC_06 is configured as FLEXPWM2_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_07_FLEXPWM2_PWMB00,     /* GPIO_EMC_07 is configured as FLEXPWM2_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_08_FLEXPWM2_PWMA01,     /* GPIO_EMC_08 is configured as FLEXPWM2_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_09_FLEXPWM2_PWMB01,     /* GPIO_EMC_09 is configured as FLEXPWM2_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_23_FLEXPWM1_PWMA00,     /* GPIO_EMC_23 is configured as FLEXPWM1_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_24_FLEXPWM1_PWMB00,     /* GPIO_EMC_24 is configured as FLEXPWM1_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_25_FLEXPWM1_PWMA01,     /* GPIO_EMC_25 is configured as FLEXPWM1_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_26_FLEXPWM1_PWMB01,     /* GPIO_EMC_26 is configured as FLEXPWM1_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_27_FLEXPWM1_PWMA02,     /* GPIO_EMC_27 is configured as FLEXPWM1_PWMA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_28_FLEXPWM1_PWMB02,     /* GPIO_EMC_28 is configured as FLEXPWM1_PWMB02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_29_FLEXPWM3_PWMA00,     /* GPIO_EMC_29 is configured as FLEXPWM3_PWMA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_30_FLEXPWM3_PWMB00,     /* GPIO_EMC_30 is configured as FLEXPWM3_PWMB00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_31_FLEXPWM3_PWMA01,     /* GPIO_EMC_31 is configured as FLEXPWM3_PWMA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_32_FLEXPWM3_PWMB01,     /* GPIO_EMC_32 is configured as FLEXPWM3_PWMB01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_33_FLEXPWM3_PWMA02,     /* GPIO_EMC_33 is configured as FLEXPWM3_PWMA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_34_FLEXPWM3_PWMB02,     /* GPIO_EMC_34 is configured as FLEXPWM3_PWMB02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEncPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E5, peripheral: ENC1, signal: 'PHASE, A', pin_signal: GPIO_EMC_35}
  - {pin_num: C3, peripheral: ENC1, signal: 'PHASE, B', pin_signal: GPIO_EMC_36}
  - {pin_num: E4, peripheral: ENC1, signal: INDEX, pin_signal: GPIO_EMC_37}
  - {pin_num: A6, peripheral: ENC2, signal: 'PHASE, A', pin_signal: GPIO_EMC_13}
  - {pin_num: B6, peripheral: ENC2, signal: 'PHASE, B', pin_signal: GPIO_EMC_14}
  - {pin_num: E11, peripheral: ENC2, signal: INDEX, pin_signal: GPIO_B0_15}
  - {pin_num: B1, peripheral: ENC3, signal: 'PHASE, A', pin_signal: GPIO_EMC_15}
  - {pin_num: A5, peripheral: ENC3, signal: 'PHASE, B', pin_signal: GPIO_EMC_16}
  - {pin_num: A11, peripheral: ENC3, signal: INDEX, pin_signal: GPIO_B1_00}
  - {pin_num: B11, peripheral: ENC4, signal: 'PHASE, A', pin_signal: GPIO_B1_01}
  - {pin_num: C11, peripheral: ENC4, signal: 'PHASE, B', pin_signal: GPIO_B1_02}
  - {pin_num: D11, peripheral: ENC4, signal: INDEX, pin_signal: GPIO_B1_03}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEncPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEncPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */
  CLOCK_EnableClock(kCLOCK_Xbar1);            /* xbar1 clock (xbar1_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_15_XBAR1_INOUT13,        /* GPIO_B0_15 is configured as XBAR1_INOUT13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_00_XBAR1_INOUT14,        /* GPIO_B1_00 is configured as XBAR1_INOUT14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_01_XBAR1_INOUT15,        /* GPIO_B1_01 is configured as XBAR1_INOUT15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_02_XBAR1_INOUT16,        /* GPIO_B1_02 is configured as XBAR1_INOUT16 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_03_XBAR1_INOUT17,        /* GPIO_B1_03 is configured as XBAR1_INOUT17 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_13_XBAR1_IN25,          /* GPIO_EMC_13 is configured as XBAR1_IN25 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_14_XBAR1_INOUT19,       /* GPIO_EMC_14 is configured as XBAR1_INOUT19 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_15_XBAR1_IN20,          /* GPIO_EMC_15 is configured as XBAR1_IN20 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_16_XBAR1_IN21,          /* GPIO_EMC_16 is configured as XBAR1_IN21 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_35_XBAR1_INOUT18,       /* GPIO_EMC_35 is configured as XBAR1_INOUT18 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_36_XBAR1_IN22,          /* GPIO_EMC_36 is configured as XBAR1_IN22 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_37_XBAR1_IN23,          /* GPIO_EMC_37 is configured as XBAR1_IN23 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR6 = ((IOMUXC_GPR->GPR6 &
    (~(IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_13_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_14_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_15_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_16_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_18_MASK | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_19_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_13(0x00u) /* IOMUXC XBAR_INOUT13 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_14(0x00u) /* IOMUXC XBAR_INOUT14 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_15(0x00u) /* IOMUXC XBAR_INOUT15 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_16(0x00u) /* IOMUXC XBAR_INOUT16 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_17(0x00u) /* IOMUXC XBAR_INOUT17 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_18(0x00u) /* IOMUXC XBAR_INOUT18 function direction select: 0x00u */
      | IOMUXC_GPR_GPR6_IOMUXC_XBAR_DIR_SEL_19(0x00u) /* IOMUXC XBAR_INOUT19 function direction select: 0x00u */
    );
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout18, kXBARA1_OutputEnc1PhaseAInput); /* IOMUX_XBAR_INOUT18 output assigned to XBARA1_IN18 input is connected to XBARA1_OUT66 output assigned to ENC1_PHASE_A_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn22, kXBARA1_OutputEnc1PhaseBInput); /* IOMUX_XBAR_IN22 output assigned to XBARA1_IN22 input is connected to XBARA1_OUT67 output assigned to ENC1_PHASE_B_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn23, kXBARA1_OutputEnc1Index); /* IOMUX_XBAR_IN23 output assigned to XBARA1_IN23 input is connected to XBARA1_OUT68 output assigned to ENC1_INDEX */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn25, kXBARA1_OutputEnc2PhaseAInput); /* IOMUX_XBAR_IN25 output assigned to XBARA1_IN25 input is connected to XBARA1_OUT71 output assigned to ENC2_PHASE_A_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout19, kXBARA1_OutputEnc2PhaseBInput); /* IOMUX_XBAR_INOUT19 output assigned to XBARA1_IN19 input is connected to XBARA1_OUT72 output assigned to ENC2_PHASE_B_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout13, kXBARA1_OutputEnc2Index); /* IOMUX_XBAR_INOUT13 output assigned to XBARA1_IN13 input is connected to XBARA1_OUT73 output assigned to ENC2_INDEX */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn20, kXBARA1_OutputEnc3PhaseAInput); /* IOMUX_XBAR_IN20 output assigned to XBARA1_IN20 input is connected to XBARA1_OUT76 output assigned to ENC3_PHASE_A_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarIn21, kXBARA1_OutputEnc3PhaseBInput); /* IOMUX_XBAR_IN21 output assigned to XBARA1_IN21 input is connected to XBARA1_OUT77 output assigned to ENC3_PHASE_B_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout14, kXBARA1_OutputEnc3Index); /* IOMUX_XBAR_INOUT14 output assigned to XBARA1_IN14 input is connected to XBARA1_OUT78 output assigned to ENC3_INDEX */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout15, kXBARA1_OutputEnc4PhaseAInput); /* IOMUX_XBAR_INOUT15 output assigned to XBARA1_IN15 input is connected to XBARA1_OUT81 output assigned to ENC4_PHASE_A_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout16, kXBARA1_OutputEnc4PhaseBInput); /* IOMUX_XBAR_INOUT16 output assigned to XBARA1_IN16 input is connected to XBARA1_OUT82 output assigned to ENC4_PHASE_B_INPUT */
  XBARA_SetSignalsConnection(XBARA1, kXBARA1_InputIomuxXbarInout17, kXBARA1_OutputEnc4Index); /* IOMUX_XBAR_INOUT17 output assigned to XBARA1_IN17 input is connected to XBARA1_OUT83 output assigned to ENC4_INDEX */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLcdPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D7, peripheral: LCDIF, signal: lcdif_clk, pin_signal: GPIO_B0_00}
  - {pin_num: E7, peripheral: LCDIF, signal: lcdif_enable, pin_signal: GPIO_B0_01}
  - {pin_num: E8, peripheral: LCDIF, signal: lcdif_hsync, pin_signal: GPIO_B0_02}
  - {pin_num: D8, peripheral: LCDIF, signal: lcdif_vsync, pin_signal: GPIO_B0_03}
  - {pin_num: C8, peripheral: LCDIF, signal: 'lcdif_data, 00', pin_signal: GPIO_B0_04}
  - {pin_num: B8, peripheral: LCDIF, signal: 'lcdif_data, 01', pin_signal: GPIO_B0_05}
  - {pin_num: A8, peripheral: LCDIF, signal: 'lcdif_data, 02', pin_signal: GPIO_B0_06}
  - {pin_num: A9, peripheral: LCDIF, signal: 'lcdif_data, 03', pin_signal: GPIO_B0_07}
  - {pin_num: B9, peripheral: LCDIF, signal: 'lcdif_data, 04', pin_signal: GPIO_B0_08}
  - {pin_num: C9, peripheral: LCDIF, signal: 'lcdif_data, 05', pin_signal: GPIO_B0_09}
  - {pin_num: D9, peripheral: LCDIF, signal: 'lcdif_data, 06', pin_signal: GPIO_B0_10}
  - {pin_num: A10, peripheral: LCDIF, signal: 'lcdif_data, 07', pin_signal: GPIO_B0_11}
  - {pin_num: G10, peripheral: GPIO1, signal: 'gpio_io, 11', pin_signal: GPIO_AD_B0_11, direction: INPUT}
  - {pin_num: A7, peripheral: GPIO3, signal: 'gpio_io, 26', pin_signal: GPIO_EMC_40, direction: OUTPUT}
  - {pin_num: F13, peripheral: GPIO1, signal: 'gpio_io, 08', pin_signal: GPIO_AD_B0_08, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLcdPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLcdPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_08_GPIO1_IO08,        /* GPIO_AD_B0_08 is configured as GPIO1_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_11_GPIO1_IO11,        /* GPIO_AD_B0_11 is configured as GPIO1_IO11 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_00_LCD_CLK,              /* GPIO_B0_00 is configured as LCD_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_01_LCD_ENABLE,           /* GPIO_B0_01 is configured as LCD_ENABLE */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_02_LCD_HSYNC,            /* GPIO_B0_02 is configured as LCD_HSYNC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_03_LCD_VSYNC,            /* GPIO_B0_03 is configured as LCD_VSYNC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_04_LCD_DATA00,           /* GPIO_B0_04 is configured as LCD_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_05_LCD_DATA01,           /* GPIO_B0_05 is configured as LCD_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_06_LCD_DATA02,           /* GPIO_B0_06 is configured as LCD_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_07_LCD_DATA03,           /* GPIO_B0_07 is configured as LCD_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_08_LCD_DATA04,           /* GPIO_B0_08 is configured as LCD_DATA04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_09_LCD_DATA05,           /* GPIO_B0_09 is configured as LCD_DATA05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_10_LCD_DATA06,           /* GPIO_B0_10 is configured as LCD_DATA06 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_11_LCD_DATA07,           /* GPIO_B0_11 is configured as LCD_DATA07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_00_LCD_CLK,              /* GPIO_B0_00 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_01_LCD_ENABLE,           /* GPIO_B0_01 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_02_LCD_HSYNC,            /* GPIO_B0_02 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_03_LCD_VSYNC,            /* GPIO_B0_03 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_04_LCD_DATA00,           /* GPIO_B0_04 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_05_LCD_DATA01,           /* GPIO_B0_05 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_06_LCD_DATA02,           /* GPIO_B0_06 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_07_LCD_DATA03,           /* GPIO_B0_07 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_08_LCD_DATA04,           /* GPIO_B0_08 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_09_LCD_DATA05,           /* GPIO_B0_09 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_10_LCD_DATA06,           /* GPIO_B0_10 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_11_LCD_DATA07,           /* GPIO_B0_11 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_40_GPIO3_IO26,          /* GPIO_EMC_40 is configured as GPIO3_IO26 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_11_GPIO1_IO11,        /* GPIO_AD_B0_11 PAD functional properties : */
      0x70A0u);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/4
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 47K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCanPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A4, peripheral: CAN1, signal: TX, pin_signal: GPIO_EMC_17}
  - {pin_num: B2, peripheral: CAN1, signal: RX, pin_signal: GPIO_EMC_18}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCanPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCanPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_17_FLEXCAN1_TX,         /* GPIO_EMC_17 is configured as FLEXCAN1_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_18_FLEXCAN1_RX,         /* GPIO_EMC_18 is configured as FLEXCAN1_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEnetPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E12, peripheral: ENET, signal: 'enet_rx_data, 0', pin_signal: GPIO_B1_04}
  - {pin_num: D12, peripheral: ENET, signal: 'enet_rx_data, 1', pin_signal: GPIO_B1_05}
  - {pin_num: C12, peripheral: ENET, signal: enet_rx_en, pin_signal: GPIO_B1_06}
  - {pin_num: B12, peripheral: ENET, signal: 'enet_tx_data, 0', pin_signal: GPIO_B1_07}
  - {pin_num: A12, peripheral: ENET, signal: 'enet_tx_data, 1', pin_signal: GPIO_B1_08}
  - {pin_num: A13, peripheral: ENET, signal: enet_tx_en, pin_signal: GPIO_B1_09}
  - {pin_num: B13, peripheral: ENET, signal: enet_tx_clk, pin_signal: GPIO_B1_10}
  - {pin_num: C13, peripheral: ENET, signal: enet_rx_er, pin_signal: GPIO_B1_11}
  - {pin_num: C14, peripheral: ENET, signal: enet_mdc, pin_signal: GPIO_B1_14}
  - {pin_num: B14, peripheral: ENET, signal: enet_mdio, pin_signal: GPIO_B1_15}
  - {pin_num: F14, peripheral: GPIO1, signal: 'gpio_io, 09', pin_signal: GPIO_AD_B0_09, direction: OUTPUT}
  - {pin_num: G13, peripheral: GPIO1, signal: 'gpio_io, 10', pin_signal: GPIO_AD_B0_10, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEnetPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEnetPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_09_GPIO1_IO09,        /* GPIO_AD_B0_09 is configured as GPIO1_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_10_GPIO1_IO10,        /* GPIO_AD_B0_10 is configured as GPIO1_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_04_ENET_RX_DATA00,       /* GPIO_B1_04 is configured as ENET_RX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_05_ENET_RX_DATA01,       /* GPIO_B1_05 is configured as ENET_RX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_06_ENET_RX_EN,           /* GPIO_B1_06 is configured as ENET_RX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_07_ENET_TX_DATA00,       /* GPIO_B1_07 is configured as ENET_TX_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_08_ENET_TX_DATA01,       /* GPIO_B1_08 is configured as ENET_TX_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_09_ENET_TX_EN,           /* GPIO_B1_09 is configured as ENET_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_10_ENET_REF_CLK,          /* GPIO_B1_10 is configured as ENET_REF_CLK */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_11_ENET_RX_ER,           /* GPIO_B1_11 is configured as ENET_RX_ER */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_14_ENET_MDC,             /* GPIO_B1_14 is configured as ENET_MDC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_15_ENET_MDIO,            /* GPIO_B1_15 is configured as ENET_MDIO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  
    IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_09_GPIO1_IO09,        /* GPIO_AD_B0_09 PAD functional properties : */
      0xB0A9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_10_GPIO1_IO10,        /* GPIO_AD_B0_10 PAD functional properties : */
      0xB0A9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  
    IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_04_ENET_RX_DATA00,       /* GPIO_B1_04 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_05_ENET_RX_DATA01,       /* GPIO_B1_05 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_06_ENET_RX_EN,           /* GPIO_B1_06 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_07_ENET_TX_DATA00,       /* GPIO_B1_07 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_08_ENET_TX_DATA01,       /* GPIO_B1_08 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_09_ENET_TX_EN,           /* GPIO_B1_09 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_10_ENET_REF_CLK,         /* GPIO_B1_10 PAD functional properties : */
      0x31u);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: low(50MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Disabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_11_ENET_RX_ER,           /* GPIO_B1_11 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_14_ENET_MDC,            /* GPIO_EMC_40 PAD functional properties : */
      0xB0E9u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: max(200MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B1_15_ENET_MDIO,           /* GPIO_EMC_41 PAD functional properties : */
      0xB829u);                               /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: R0/5
                                                 Speed Field: low(50MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexSPIPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L5, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA3, pin_signal: GPIO_SD_B1_00}
  - {pin_num: M5, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA2, pin_signal: GPIO_SD_B1_01}
  - {pin_num: M3, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA1, pin_signal: GPIO_SD_B1_02}
  - {pin_num: M4, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA0, pin_signal: GPIO_SD_B1_03}
  - {pin_num: P2, peripheral: FLEXSPI, signal: FLEXSPI_B_SCLK, pin_signal: GPIO_SD_B1_04}
  - {pin_num: N3, peripheral: FLEXSPI, signal: FLEXSPI_B_SS0_B, pin_signal: GPIO_SD_B1_05}
  - {pin_num: L3, peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B1_06}
  - {pin_num: L4, peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B1_07}
  - {pin_num: P3, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B1_08}
  - {pin_num: N4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B1_09}
  - {pin_num: P4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B1_10}
  - {pin_num: P5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B1_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFlexSPIPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_00_FLEXSPIB_DATA03,   /* GPIO_SD_B1_00 is configured as FLEXSPIB_DATA03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_01_FLEXSPIB_DATA02,   /* GPIO_SD_B1_01 is configured as FLEXSPIB_DATA02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_02_FLEXSPIB_DATA01,   /* GPIO_SD_B1_02 is configured as FLEXSPIB_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_03_FLEXSPIB_DATA00,   /* GPIO_SD_B1_03 is configured as FLEXSPIB_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_04_FLEXSPIB_SCLK,     /* GPIO_SD_B1_04 is configured as FLEXSPIB_SCLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_05_FLEXSPIB_SS0_B,    /* GPIO_SD_B1_05 is configured as FLEXSPIB_SS0_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B,    /* GPIO_SD_B1_06 is configured as FLEXSPIA_SS0_B */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK,     /* GPIO_SD_B1_07 is configured as FLEXSPIA_SCLK */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00,   /* GPIO_SD_B1_08 is configured as FLEXSPIA_DATA00 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01,   /* GPIO_SD_B1_09 is configured as FLEXSPIA_DATA01 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02,   /* GPIO_SD_B1_10 is configured as FLEXSPIA_DATA02 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03,   /* GPIO_SD_B1_11 is configured as FLEXSPIA_DATA03 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUsdhcPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D13, peripheral: USDHC1, signal: usdhc_cd_b, pin_signal: GPIO_B1_12}
  - {pin_num: J4, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: GPIO_SD_B0_00}
  - {pin_num: J3, peripheral: USDHC1, signal: usdhc_clk, pin_signal: GPIO_SD_B0_01}
  - {pin_num: J1, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: GPIO_SD_B0_02}
  - {pin_num: K1, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: GPIO_SD_B0_03}
  - {pin_num: H2, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: GPIO_SD_B0_04}
  - {pin_num: J2, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: GPIO_SD_B0_05}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUsdhcPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUsdhcPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_12_USDHC1_CD_B,          /* GPIO_B1_12 is configured as USDHC1_CD_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_00_USDHC1_CMD,        /* GPIO_SD_B0_00 is configured as USDHC1_CMD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_01_USDHC1_CLK,        /* GPIO_SD_B0_01 is configured as USDHC1_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_02_USDHC1_DATA0,      /* GPIO_SD_B0_02 is configured as USDHC1_DATA0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_03_USDHC1_DATA1,      /* GPIO_SD_B0_03 is configured as USDHC1_DATA1 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_04_USDHC1_DATA2,      /* GPIO_SD_B0_04 is configured as USDHC1_DATA2 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B0_05_USDHC1_DATA3,      /* GPIO_SD_B0_05 is configured as USDHC1_DATA3 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUartPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B4, peripheral: LPUART4, signal: TX, pin_signal: GPIO_EMC_19}
  - {pin_num: A3, peripheral: LPUART4, signal: RX, pin_signal: GPIO_EMC_20}
  - {pin_num: M11, peripheral: LPUART6, signal: TX, pin_signal: GPIO_AD_B0_02}
  - {pin_num: G11, peripheral: LPUART6, signal: RX, pin_signal: GPIO_AD_B0_03}
  - {pin_num: D6, peripheral: GPIO3, signal: 'gpio_io, 24', pin_signal: GPIO_EMC_38, direction: OUTPUT}
  - {pin_num: B7, peripheral: GPIO3, signal: 'gpio_io, 25', pin_signal: GPIO_EMC_39, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUartPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUartPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_02_LPUART6_TX,        /* GPIO_AD_B0_02 is configured as LPUART6_TX */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_03_LPUART6_RX,        /* GPIO_AD_B0_03 is configured as LPUART6_RX */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_19_LPUART4_TX,          /* GPIO_EMC_19 is configured as LPUART4_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_20_LPUART4_RX,          /* GPIO_EMC_20 is configured as LPUART4_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_38_GPIO3_IO24,          /* GPIO_EMC_38 is configured as GPIO3_IO24 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_39_GPIO3_IO25,          /* GPIO_EMC_39 is configured as GPIO3_IO25 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2cPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C1, peripheral: LPI2C3, signal: SDA, pin_signal: GPIO_EMC_21}
  - {pin_num: F1, peripheral: LPI2C3, signal: SCL, pin_signal: GPIO_EMC_22}
  - {pin_num: G3, peripheral: LPI2C4, signal: SDA, pin_signal: GPIO_EMC_11}
  - {pin_num: H1, peripheral: LPI2C4, signal: SCL, pin_signal: GPIO_EMC_12}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2cPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitI2cPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_11_LPI2C4_SDA,          /* GPIO_EMC_11 is configured as LPI2C4_SDA */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_12_LPI2C4_SCL,          /* GPIO_EMC_12 is configured as LPI2C4_SCL */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_21_LPI2C3_SDA,          /* GPIO_EMC_21 is configured as LPI2C3_SDA */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_22_LPI2C3_SCL,          /* GPIO_EMC_22 is configured as LPI2C3_SCL */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_11_LPI2C4_SDA,          /* IOMUXC_GPIO_EMC_11 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate 0xF0F8u
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_12_LPI2C4_SCL,          /* IOMUXC_GPIO_EMC_12 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */

  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_21_LPI2C3_SDA,          /* IOMUXC_GPIO_EMC_21 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate 0xF0F8u
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_22_LPI2C3_SCL,          /* IOMUXC_GPIO_EMC_22 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSwdPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E14, peripheral: JTAG, signal: TMS, pin_signal: GPIO_AD_B0_06}
  - {pin_num: F12, peripheral: JTAG, signal: TCK, pin_signal: GPIO_AD_B0_07}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSwdPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSwdPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_06_JTAG_TMS,          /* GPIO_AD_B0_06 is configured as JTAG_TMS */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_07_JTAG_TCK,          /* GPIO_AD_B0_07 is configured as JTAG_TCK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUserButtonPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: F11, peripheral: GPIO1, signal: 'gpio_io, 04', pin_signal: GPIO_AD_B0_04, direction: INPUT}
  - {pin_num: G14, peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO_AD_B0_05, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUserButtonPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUserButtonPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_04_GPIO1_IO04,        /* GPIO_AD_B0_04 is configured as GPIO1_IO04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_05_GPIO1_IO05,        /* GPIO_AD_B0_05 is configured as GPIO1_IO05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUserLedPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D10, peripheral: GPIO2, signal: 'gpio_io, 13', pin_signal: GPIO_B0_13, direction: OUTPUT}
  - {pin_num: E10, peripheral: GPIO2, signal: 'gpio_io, 14', pin_signal: GPIO_B0_14, direction: OUTPUT}
  - {pin_num: C7, peripheral: GPIO3, signal: 'gpio_io, 27', pin_signal: GPIO_EMC_41}
  - {pin_num: G1, peripheral: GPIO4, signal: 'gpio_io, 10', pin_signal: GPIO_EMC_10, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUserLedPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUserLedPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_13_GPIO2_IO13,           /* GPIO_B0_13 is configured as GPIO2_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_14_GPIO2_IO14,           /* GPIO_B0_14 is configured as GPIO2_IO14 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_10_GPIO4_IO10,          /* GPIO_EMC_10 is configured as GPIO4_IO10 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_41_GPIO3_IO27,          /* GPIO_EMC_41 is configured as GPIO3_IO27 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitAdditionalPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C10, peripheral: GPIO2, signal: 'gpio_io, 12', pin_signal: GPIO_B0_12, direction: OUTPUT}
  - {pin_num: L7, peripheral: GPIO5, signal: 'gpio_io, 02', pin_signal: PMIC_STBY_REQ, direction: OUTPUT}
  - {pin_num: L6, peripheral: GPIO5, signal: 'gpio_io, 00', pin_signal: WAKEUP}
  - {pin_num: D14, peripheral: WDOG1, signal: wdog_b, pin_signal: GPIO_B1_13}
  - {pin_num: K7, peripheral: GPIO5, signal: 'gpio_io, 01', pin_signal: PMIC_ON_REQ}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitAdditionalPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitAdditionalPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */
  CLOCK_EnableClock(kCLOCK_IomuxcSnvs);       /* iomuxc_snvs clock (iomuxc_snvs_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_12_GPIO2_IO12,           /* GPIO_B0_12 is configured as GPIO2_IO12 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_13_WDOG1_B,              /* GPIO_B1_13 is configured as WDOG1_B */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_SNVS_PMIC_ON_REQ_GPIO5_IO01,     /* PMIC_ON_REQ is configured as GPIO5_IO01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_SNVS_PMIC_STBY_REQ_GPIO5_IO02,   /* PMIC_STBY_REQ is configured as GPIO5_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_SNVS_WAKEUP_GPIO5_IO00,          /* WAKEUP is configured as GPIO5_IO00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_DeinitNfcPins
 * Description   : Reonfigures LCD pins to I2C (NCF based) pins.
 *
 * END ****************************************************************************************************************/
void BOARD_InitNfcPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_08_GPIO2_IO08,           /* GPIO_B0_08 is configured as GPIO2_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_09_GPIO2_IO09,           /* GPIO_B0_09 is configured as GPIO2_IO09 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_04_LPI2C2_SCL,           /* GPIO_B0_04 is configured as LCD_DATA00 */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_05_LPI2C2_SDA,           /* GPIO_B0_05 is configured as LCD_DATA01 */
      1U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_04_LPI2C2_SCL,           /* GPIO_B0_04 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate 0xF0F8u
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_05_LPI2C2_SDA,           /* GPIO_B0_05 PAD functional properties : */
      0xF8B0u);                               /* Slew Rate Field: Slow Slew Rate 0xF8B0u
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Enabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 22K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Disabled */
  }

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_DeinitNfcPins
 * Description   : Reconfigures pin I2C (NFC based) pins back to lcd pins.
 *
 * END ****************************************************************************************************************/
void BOARD_DeinitNfcPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_04_LCD_DATA00,           /* GPIO_B0_04 is configured as LCD_DATA00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_05_LCD_DATA01,           /* GPIO_B0_05 is configured as LCD_DATA01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_08_LCD_DATA04,           /* GPIO_B0_08 is configured as LCD_DATA04 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B0_09_LCD_DATA05,           /* GPIO_B0_09 is configured as LCD_DATA05 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_04_LCD_DATA00,           /* GPIO_B0_04 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_05_LCD_DATA01,           /* GPIO_B0_05 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_08_LCD_DATA04,           /* GPIO_B0_04 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B0_09_LCD_DATA05,           /* GPIO_B0_05 PAD functional properties : */
      0x01B0B0u);                             /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Pull
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Up
                                                 Hyst. Enable Field: Hysteresis Enabled */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
